// =========================================================================
// BANCO DE DADOS COMPLETO - ESTRUTURA 100% ESTÁTICA PARA EDIÇÃO DIRETA
// =========================================================================

const dadosAluno = {
    usuario: {
        username: "loneke", 
        senha: "123",      
        nome: "Loneke",
        email: "loneke@gmail.com"
    },
    cursos: [
        {
            id: 1,
            titulo: "CURSO COMPLETO DE COMO GANHAR NO MINIMO 50.000KZ POR SEMANA CRIANDO ARTES COM INTELIGENCIA ARTIFICIAL",
            imagem: "../img/prontos/CURSO COMO GANHAR NO MINIMO 50.000KZ POR MÊS CRIANDO ARTES GRAFICA + TRAFEGO PAGO.jpg",
            desbloqueado: false,
            linkMaterial: "https://mediafire.com/exemplo",
            modulos: [
                { nome: "01. COMECE AQUI", aulas: [{ titulo: "OBRIGADO", url: "LINK_AQUI" }, { titulo: "COMO VAI FUNCIONAR O CURSO", url: "LINK_AQUI" }] },
                { nome: "02. INTRODUÇÃO", aulas: [{ titulo: "AULA 01 - INTRODUÇÃO AO CURSO DE ARTES GRAFICAS ", url: "LINK_AQUI" }] },
                { nome: "03. CRIAÇÃO DE CONTAS", aulas: [{ titulo: "AULA 01 - COMO CRIAR UMA CONTA DE EMAIL", url: "LINK_AQUI" }, { titulo: "AULA 02 - COMO INSTALAR OS PROGRAMAS QUE VAMOS USAR NA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "AULA 03 - COMO CRIAR UMA CONTA NO CHATGPT", url: "LINK_AQUI" }, { titulo: "AULA 04 - COMO CRIAR UMA CONTA NO WHATSAP", url: "LINK_AQUI" }, { titulo: "AULA 05 - COMO CRIAR UMA PAGINA NO FACEBOOK", url: "LINK_AQUI" }] },
                { nome: "04. CRIAÇÃO DE ARTES (COM INTELIGENCIA ARTIFICIAL)", aulas: [{ titulo: "AULA 01 - COMO CRIAR CAPA DO ZERO PARA UMA MUSICA", url: "LINK_AQUI" }, { titulo: "AULA 02 - COMO CRIAR CAPA PARA UMA MUSICA USANDO UM MODELO", url: "LINK_AQUI" }, { titulo: "AULA 03 - COMO CRIAR LOGOTIPO", url: "LINK_AQUI" }, { titulo: "AULA 04 - FLYER DE CONFIRMAÇÃO", url: "LINK_AQUI" }, { titulo: "AULA 05 - COMO CRIAR UM FLYER OU PANFLETO", url: "LINK_AQUI" }] },
                { nome: "05. CRIAÇÃO DA CONTA VISA", aulas: [{ titulo: "AULA 01 – COMO CRIAR UMA CONTA VISA", url: "LINK_AQUI" }, { titulo: "AULA 02 – COMO ACTIVAR A SUA CONTA VISA", url: "LINK_AQUI" }, { titulo: "AULA 03 – COMO CARREGAR A SUA CONTA VISA", url: "LINK_AQUI" }] },
                { nome: "06. CRIAÇÃO E CONFIGURAÇÃO DO SEU NEGOCIO ONLINE", aulas: [{ titulo: "AULA 01 – COMO CONFIGURAR SUA PÁGINA DO FACEBOOK", url: "LINK_AQUI" }, { titulo: "AULA 02 – COMO CONFIGURAR O SEU WHATSAP", url: "LINK_AQUI" }] },
                { nome: "07. CRIANDO A PUBLICAÇÃO E O ANUNCIO", aulas: [{ titulo: "AULA 01 – COMO CRIAR UMA OFERTA", url: "LINK_AQUI" }, { titulo: "AULA 02 – COMO CRIAR UMA PUBLICAÇÃO IRRESISTIVEL", url: "LINK_AQUI" }, { titulo: "AULA 03 – SOLTAR O ANUNCIO", url: "LINK_AQUI" }] },
                { nome: "08. ATENDIMENTO AO CLIENTE (PRÁTICA)", aulas: [{ titulo: "AULA 01 – RESPONDER MENSAGEM", url: "LINK_AQUI" }] }
            ]
        },
        {
            id: 2,
            titulo: "CURSO COMPLETO DE COMO GANHAR NO MINIMO 50.000KZ POR SEMANA DISTRIBUINDO MUSICAS NAS PLATAFORMAS DIGITAIS",
            imagem: "../img/prontos/CURSO DE COMO BAIXAR DISTRIBUIR MUSICAS NAS PLATAFORMAS DE STREAM.jpg",
            desbloqueado: false,
            linkMaterial: "https://mediafire.com/exemplo",
            modulos: [
                { nome: "01. COMECE AQUI", aulas: [{ titulo: "OBRIGADO", url: "LINK_AQUI" }, { titulo: "COMO VAI FUNCIONAR O CURSO", url: "LINK_AQUI" }] },
                { nome: "02. CRIAÇÃO DE CONTAS", aulas: [{ titulo: "AULA 01 – CRIAR CONTA NO WHATSAP", url: "LINK_AQUI" }, { titulo: "AULA 02 – CRIAR A PÁGINA NO FACEBOOK", url: "LINK_AQUI" }, { titulo: "AULA 03 – CRIAR UMA CONTA DE EMAIL", url: "LINK_AQUI" }, { titulo: "AULA 04 – INSTALAR OS PROGRAMAS DA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "AULA 05 – CRIANDO CONTA NO CHATGPT", url: "LINK_AQUI" }] },
                { nome: "03. DISTRIBUIÇÃO DE MUSICAS (TUDO)", aulas: [{ titulo: "AULA 01 – CONCEITO DE DISTRIBUIDORA E QUAL É A MELHOR?", url: "LINK_AQUI" }, { titulo: "AULA 02 – COMO CRIAR A CONTA NO TOO LOST", url: "LINK_AQUI" }, { titulo: "AULA 03 – COMO VERIFICAR A CONTA NO TOO LOST", url: "LINK_AQUI" }, { titulo: "AULA 04 – COMO DISTRIBUIR A MUSICA", url: "LINK_AQUI" }] },
                { nome: "04. CRIAÇÃO E CONFIGURAÇÃO DE CONTAS", aulas: [{ titulo: "AULA 01 – CRIANDO A PAGINA DO FACEBOOK", url: "LINK_AQUI" }, { titulo: "AULA 02 - CRIANDO A CONTA NO WHATSAP BUSINESS", url: "LINK_AQUI" }, { titulo: "AULA 03 – CRIANDO O LOGOTIPO E A FOTO DE CAPA PARA SUA EMPRESA", url: "LINK_AQUI" }, { titulo: "AULA 04 – COMO CONFIGURAR A PAGINA DO FACEBOOK", url: "LINK_AQUI" }, { titulo: "AULA 05 – COMO CONFIGURAR O SEU WHATSAP BUSINESS", url: "LINK_AQUI" }] },
                { nome: "05. CRIAÇÃO DAS ARTES", aulas: [{ titulo: "AULA 01 – CRIANDO LOGOTIPO", url: "LINK_AQUI" }, { titulo: "AULA 02 – CRIANDO FLYER", url: "LINK_AQUI" }, { titulo: "AULA 03 – CRIANDO CAPA DE MUSICA", url: "LINK_AQUI" }] },
                { nome: "06. CRIAÇÃO DA CONTA VISA", aulas: [{ titulo: "AULA 01 – COMO CRIAR UMA CONTA VISA", url: "LINK_AQUI" }, { titulo: "AULA 02 – COMO ACTIVAR A SUA CONTA VISA", url: "LINK_AQUI" }, { titulo: "AULA 03 – COMO CARREGAR A SUA CONTA VISA", url: "LINK_AQUI" }] },
                { nome: "07. FAZER A PUBLICAÇÃO E SOLTAR O ANUNCIO", aulas: [{ titulo: "AULA 01 - CRIAÇÃO DA OFERTA", url: "LINK_AQUI" }, { titulo: "AULA 02 – CRIANDO A PUBLICAÇÃO", url: "LINK_AQUI" }, { titulo: "AULA 03 – SOLTAR O ANUNCIO", url: "LINK_AQUI" }] },
                { nome: "08. ATENDIMENTO AO CLIENTE (PRATICA)", aulas: [{ titulo: "AULA 01 – RESPONDER MENSAGEM", url: "LINK_AQUI" }] }
            ]
        },
        {
            id: 3,
            titulo: "CURSO COMPLETO DE PRODUÇÃO DE AFRO BEAT + MIX E MASTER NO FL STUDIO",
            imagem: "../img/prontos/DRUMKIT TABUA MISTA DE AFROBEAT.jpg",
            desbloqueado: false,
            linkMaterial: "https://mediafire.com/exemplo",
            modulos: [
                { nome: "01. COMECE AQUI", aulas: [{ titulo: "OBRIGADO", url: "LINK_AQUI" }, { titulo: "COMO VAI FUNCIONAR O CURSO E COMO BAIXAR OS PLUGINS USADOS NA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "A BASE DA PRODUÇÃO MUSICAL E EQUIPAMENTOS PARA A NOSSA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "CONCEITOS BÁSICOS SOBRE PRODUÇÃO MUSICAL", url: "LINK_AQUI" }, { titulo: "VST E VSTI", url: "LINK_AQUI" }, { titulo: "INSTALANDO OS PROGRAMA DA FORMAÇÃO", url: "LINK_AQUI" }] },
                { nome: "02. A BASE DA PRODUÇÃO MUSICAL (FL STUDIO O BÁSICO)", aulas: [{ titulo: "AULA 01 - APRESENTAÇÃO DO AMBIENTE DO FL STUDIO", url: "https://youtu.be/tcZboMaPw5c" }, { titulo: "AULA 02 - BOTÕES DE PLAY, STOP E RECORD", url: "https://youtu.be/S9cEhJMundI" }, { titulo: "AULA 03 - CHANNEL RACK", url: "https://youtu.be/PjSxV4ol6MM" }, { titulo: "AULA 04 - PIANO ROLL", url: "https://youtu.be/O8wzgTuchL8" }, { titulo: "AULA 05 - BROWSER", url: "https://youtu.be/pmUOj8FnIJs" }, { titulo: "AULA 06 - MENU", url: "https://youtu.be/c0crY-l7lBw" }, { titulo: "AULA 07 - PLAYLIST", url: "https://youtu.be/ZtYalbddMsc" }, { titulo: "AULA 08 - MIXER", url: "https://youtu.be/LAwVXwlkSbY" }, { titulo: "AULA 09 - COMO CONFIGURAR O FL STUDIO", url: "https://youtu.be/ps9Rg_XP-wU" }, { titulo: "AULA 10 - COMO ADICIONAR OS DRUMKITS DENTRO DO FL STUDIO", url: "https://youtu.be/Qr5umV3H9qI" }, { titulo: "AULA 11 - COMO SCANNEAR PLUGINS DENTRO DO FL STUDIO", url: "https://youtu.be/zUg5QchOBvM" }, { titulo: "AULA 12 - COMO GRAVAR UMA VOZ NO FL STUDIO", url: "https://youtu.be/T1-6w7Ok25o" }, { titulo: "AULA 13 - COMO REMOVER RUIDO DE UMA VOZ NO FL STUDIO", url: "https://youtu.be/pqYrZIS24Do" }, { titulo: "AULA 14 - ATALHOS NO FL STUDIO", url: "https://youtu.be/hE3CsImmPrU" }, { titulo: "AULA 15 - GRID E COMPASSOS", url: "https://youtu.be/f3yMkzRfYGA" }, { titulo: "AULA 16 - COMO ACHAR O BPM DE UMA MÚSICA", url: "https://youtu.be/QfJU7BCYi4I" }, { titulo: "AULA 17 - COMO COLOCAR QUALQUER AUDIO DENTRO DA NOTA ( VOCAL, ONE SHOT E 808 )", url: "https://youtu.be/R3xZKrng9g4" }, { titulo: "AULA 18 - COMO SEPARAR AS PARTES DE UMA MÚSICA", url: "https://youtu.be/vJcW794o5DY" }, { titulo: "AULA 19 - CHANNEL RACK AVANÇADO", url: "https://youtu.be/MFrCKJ6MLL8" }, { titulo: "AULA 20 - COMO LIGAR O CONTROLADOR MIDI", url: "https://youtu.be/4DIH2kTgP9Q" }] },
                { nome: "03. A BASE DA TEORIA MUSICAL", aulas: [{ titulo: "AULA 01 - TEORIA MUSICAL", url: "https://youtu.be/BMV2nPGwU70" }, { titulo: "AULA 02 - NOTAS MUSICAS E NOTAS DE ACIDENTE", url: "https://youtu.be/_-XMBkyz77w" }, { titulo: "AULA 03 - CIFRAS", url: "https://youtu.be/LgDAech2LiU" }, { titulo: "AULA 04 - INTERVALOS", url: "https://youtu.be/Ok-PTt11S7g" }, { titulo: "AULA 05 - ESCALAS", url: "https://youtu.be/xApa3-95rT8" }, { titulo: "AULA 06 - FORMAÇÃO DE ESCALAS", url: "https://youtu.be/JLoNI6bFkJs" }, { titulo: "AULA 07 - ACORDES", url: "https://youtu.be/TVVHJlC-BQk" }, { titulo: "AULA 08 - CRIAÇÃO DE ACORDES", url: "https://youtu.be/QL9_zGlgyYg" }, { titulo: "AULA 09 - CAMPO HARMONICO", url: "https://youtu.be/RK7s8dSHkkU" }, { titulo: "AULA 10 - CRIANDO PROGRESSÕES DE ACORDE COM CAMPO HARMONICO", url: "https://youtu.be/MqyH_WydNfg" }, { titulo: "AULA 11 - CRIAR PROGRESSÕES DE ACORDE COM APENAS UM CLIQUE", url: "https://youtu.be/n6wvtMqNGqw" }, { titulo: "AULA 12 - COMO TIRAR AS CIFRAS DE UMA MÚSICA", url: "https://youtu.be/sLevV4Je4Gk" }, { titulo: "AULA 13 - CRIANDO PROGRESSÕES DE ACORDE COM O SCALLER", url: "https://youtu.be/OVeRVWw410E" }, { titulo: "AULA 14 - SITE PARA ENCONTRAR CIFRAS DE UMA MÚSICA", url: "https://youtu.be/37qMcwzOjyU" }, { titulo: "AULA 15 - COMO COPIAR OU ROUBAR MELODIAS DE OUTRAS MÚSICAS", url: "https://youtu.be/0f-ox5FjOdg" }, { titulo: "AULA 16 - COMO ACHAR A NOTA OU ESCALA DE UM BEAT", url: "https://youtu.be/uNxZ5FU-q-g" }] },
                { nome: "04. TIMBRES", aulas: [{ titulo: "AULA 01 - O QUE É UM TIMBRE E O SEU PAPEL E OS TIPOS DE INSTRUMENTOS", url: "LINK_AQUI" }, { titulo: "AULA 02 - INSTRUMENTOS DE PERCUSSÃO", url: "LINK_AQUI" }, { titulo: "AULA 03 - INSTRUMENTOS MELODICOS", url: "LINK_AQUI" }, { titulo: "AULA 04 - INSTRUMENTOS HARMONICOS", url: "LINK_AQUI" }] },
                { nome: "05. CRIAÇÃO DE RITMOS DE INSTRUMENTOS DE PERCUSSÃO", aulas: [{ titulo: "AULA 01", url: "LINK_AQUI" }, { titulo: "AULA 02", url: "LINK_AQUI" }, { titulo: "AULA 03", url: "LINK_AQUI" }, { titulo: "AULA 04", url: "LINK_AQUI" }] },
                { nome: "06. CRIAÇÃO DE MELODIAS E HARMONIA", aulas: [{ titulo: "AULA 01", url: "LINK_AQUI" }, { titulo: "AULA 02", url: "LINK_AQUI" }, { titulo: "AULA 03", url: "LINK_AQUI" }, { titulo: "AULA 04", url: "LINK_AQUI" }] },
                { nome: "07. PRODUÇÃO DE BEATS & ESTRUTURAÇÃO (PRÁTICA)", aulas: [{ titulo: "AULA 01 – CRIANDO O BEAT 01", url: "LINK_AQUI" }, { titulo: "AULA 02 - ESTRUTURAR O BEAT 01", url: "LINK_AQUI" }, { titulo: "AULA 01 – CRIANDO O BEAT 02", url: "LINK_AQUI" }, { titulo: "AULA 02 - ESTRUTURAR O BEAT 02", url: "LINK_AQUI" }, { titulo: "AULA 01 – CRIANDO O BEAT 03", url: "LINK_AQUI" }, { titulo: "AULA 02 - ESTRUTURAR O BEAT 03", url: "LINK_AQUI" }] },
                { nome: "08. A BASE DA MIX E MASTER", aulas: [{ titulo: "AULA 01 - O QUE É MIX E MASTER", url: "LINK_AQUI" }, { titulo: "AULA 02 - BALANÇO TONAL E ANALISADOR DE ESPECTRO", url: "LINK_AQUI" }, { titulo: "AULA 03 - CRIAÇÃO DE GRUPOS", url: "LINK_AQUI" }, { titulo: "AULA 04 - EQUALIZAÇÃO (O QUE É, OS TIPOS DE EQUALIZAÇÃO, OS TIPOS DE FILTROS, OS TIPOS DE EQUALIZADORES)", url: "LINK_AQUI" }, { titulo: "AULA 05 - AS FREQUENCIAS E O PAPEL DE CADA REGIÃO", url: "LINK_AQUI" }, { titulo: "AULA 06 - COMPRESSOR (O QUE É, OS TIPOS DE COMPRESSOR, OS PARAMETROS)", url: "LINK_AQUI" }, { titulo: "AULA 07 - PRE AMPLIFICADORES", url: "LINK_AQUI" }, { titulo: "AULA 08 - SATURADORES", url: "LINK_AQUI" }, { titulo: "AULA 09 - EFEITOS (DELAY E REVERB)", url: "LINK_AQUI" }, { titulo: "AULA 10 - AUTO TUNE (CORRETOR DE NOTAS)", url: "LINK_AQUI" }, { titulo: "AULA 12 - AUTOMAÇÃO", url: "LINK_AQUI" }, { titulo: "AULA 12 - LIMITER E CLIPPER", url: "LINK_AQUI" }, { titulo: "AULA 13 - SIDE CHAN", url: "LINK_AQUI" }, { titulo: "AULA 14 - IMAGEM STEREO", url: "LINK_AQUI" }] },
                { nome: "09. MIX E MASTER (PRATICA)", aulas: [{ titulo: "AULA 01 - EXPORTAR OS STEAM DE UM BEAT/PROJECTO", url: "LINK_AQUI" }, { titulo: "AULA 02 - ORGANIZAR O PROJECTO PARA MIX E MASTER", url: "LINK_AQUI" }, { titulo: "AULA 03 - MIXAR O PRIMEIRO BEAT DO PRINCIPIO ATÉ AO FIM ", url: "LINK_AQUI" }, { titulo: "AULA 04 – COMO MASTERIZAR O PRIMEIRO BEAT", url: "LINK_AQUI" }, { titulo: "AULA 05- MIXAR O SEGUNDO BEAT DO PRINCIPIO ATÉ AO FIM ", url: "LINK_AQUI" }, { titulo: "AULA 06 – COMO MASTERIZAR O SEGUNDO BEAT", url: "LINK_AQUI" }] }
            ]
        },
        {
            id: 4,
            titulo: "CURSO COMPLETO DE PRODUÇÃO DE AFRO HOUSE + MIX E MASTER NO FL STUDIO",
            imagem: "../img/prontos/CURSO DE PRODUÇÃO DE BEATS DE AFRO HOUSE KUDURO DE ANGOLA MIX E MASTER NO FL STUDIO.jpg",
            desbloqueado: false,
            linkMaterial: "https://mediafire.com/exemplo",
            modulos: [
                { nome: "01. COMECE AQUI", aulas: [{ titulo: "OBRIGADO", url: "LINK_AQUI" }, { titulo: "COMO VAI FUNCIONAR O CURSO E COMO BAIXAR OS PLUGINS USADOS NA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "A BASE DA PRODUÇÃO MUSICAL E EQUIPAMENTOS PARA A NOSSA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "CONCEITOS BÁSICOS SOBRE PRODUÇÃO MUSICAL", url: "LINK_AQUI" }, { titulo: "VST E VSTI", url: "LINK_AQUI" }, { titulo: "INSTALANDO OS PROGRAMA DA FORMAÇÃO", url: "LINK_AQUI" }] },
                { nome: "02. A BASE DA PRODUÇÃO MUSICAL (FL STUDIO O BÁSICO)", aulas: [{ titulo: "AULA 01 - APRESENTAÇÃO DO AMBIENTE DO FL STUDIO", url: "https://youtu.be/tcZboMaPw5c" }, { titulo: "AULA 02 - BOTÕES DE PLAY, STOP E RECORD", url: "https://youtu.be/S9cEhJMundI" }, { titulo: "AULA 03 - CHANNEL RACK", url: "https://youtu.be/PjSxV4ol6MM" }, { titulo: "AULA 04 - PIANO ROLL", url: "https://youtu.be/O8wzgTuchL8" }, { titulo: "AULA 05 - BROWSER", url: "https://youtu.be/pmUOj8FnIJs" }, { titulo: "AULA 06 - MENU", url: "https://youtu.be/c0crY-l7lBw" }, { titulo: "AULA 07 - PLAYLIST", url: "https://youtu.be/ZtYalbddMsc" }, { titulo: "AULA 08 - MIXER", url: "https://youtu.be/LAwVXwlkSbY" }, { titulo: "AULA 09 - COMO CONFIGURAR O FL STUDIO", url: "https://youtu.be/ps9Rg_XP-wU" }, { titulo: "AULA 10 - COMO ADICIONAR OS DRUMKITS DENTRO DO FL STUDIO", url: "https://youtu.be/Qr5umV3H9qI" }, { titulo: "AULA 11 - COMO SCANNEAR PLUGINS DENTRO DO FL STUDIO", url: "https://youtu.be/zUg5QchOBvM" }, { titulo: "AULA 12 - COMO GRAVAR UMA VOZ NO FL STUDIO", url: "https://youtu.be/T1-6w7Ok25o" }, { titulo: "AULA 13 - COMO REMOVER RUIDO DE UMA VOZ NO FL STUDIO", url: "https://youtu.be/pqYrZIS24Do" }, { titulo: "AULA 14 - ATALHOS NO FL STUDIO", url: "https://youtu.be/hE3CsImmPrU" }, { titulo: "AULA 15 - GRID E COMPASSOS", url: "https://youtu.be/f3yMkzRfYGA" }, { titulo: "AULA 16 - COMO ACHAR O BPM DE UMA MÚSICA", url: "https://youtu.be/QfJU7BCYi4I" }, { titulo: "AULA 17 - COMO COLOCAR QUALQUER AUDIO DENTRO DA NOTA ( VOCAL, ONE SHOT E 808 )", url: "https://youtu.be/R3xZKrng9g4" }, { titulo: "AULA 18 - COMO SEPARAR AS PARTES DE UMA MÚSICA", url: "https://youtu.be/vJcW794o5DY" }, { titulo: "AULA 19 - CHANNEL RACK AVANÇADO", url: "https://youtu.be/MFrCKJ6MLL8" }, { titulo: "AULA 20 - COMO LIGAR O CONTROLADOR MIDI", url: "https://youtu.be/4DIH2kTgP9Q" }] },
                { nome: "03. A BASE DA TEORIA MUSICAL", aulas: [{ titulo: "AULA 01 - TEORIA MUSICAL", url: "https://youtu.be/BMV2nPGwU70" }, { titulo: "AULA 02 - NOTAS MUSICAS E NOTAS DE ACIDENTE", url: "https://youtu.be/_-XMBkyz77w" }, { titulo: "AULA 03 - CIFRAS", url: "https://youtu.be/LgDAech2LiU" }, { titulo: "AULA 04 - INTERVALOS", url: "https://youtu.be/Ok-PTt11S7g" }, { titulo: "AULA 05 - ESCALAS", url: "https://youtu.be/xApa3-95rT8" }, { titulo: "AULA 06 - FORMAÇÃO DE ESCALAS", url: "https://youtu.be/JLoNI6bFkJs" }, { titulo: "AULA 07 - ACORDES", url: "https://youtu.be/TVVHJlC-BQk" }, { titulo: "AULA 08 - CRIAÇÃO DE ACORDES", url: "https://youtu.be/QL9_zGlgyYg" }, { titulo: "AULA 09 - CAMPO HARMONICO", url: "https://youtu.be/RK7s8dSHkkU" }, { titulo: "AULA 10 - CRIANDO PROGRESSÕES DE ACORDE COM CAMPO HARMONICO", url: "https://youtu.be/MqyH_WydNfg" }, { titulo: "AULA 11 - CRIAR PROGRESSÕES DE ACORDE COM APENAS UM CLIQUE", url: "https://youtu.be/n6wvtMqNGqw" }, { titulo: "AULA 12 - COMO TIRAR AS CIFRAS DE UMA MÚSICA", url: "https://youtu.be/sLevV4Je4Gk" }, { titulo: "AULA 13 - CRIANDO PROGRESSÕES DE ACORDE COM O SCALLER", url: "https://youtu.be/OVeRVWw410E" }, { titulo: "AULA 14 - SITE PARA ENCONTRAR CIFRAS DE UMA MÚSICA", url: "https://youtu.be/37qMcwzOjyU" }, { titulo: "AULA 15 - COMO COPIAR OU ROUBAR MELODIAS DE OUTRAS MÚSICAS", url: "https://youtu.be/0f-ox5FjOdg" }, { titulo: "AULA 16 - COMO ACHAR A NOTA OU ESCALA DE UM BEAT", url: "https://youtu.be/uNxZ5FU-q-g" }] },
                { nome: "04. TIMBRES", aulas: [{ titulo: "AULA 01 - O QUE É UM TIMBRE E O SEU PAPEL E OS TIPOS DE INSTRUMENTOS", url: "LINK_AQUI" }, { titulo: "AULA 02 - INSTRUMENTOS DE PERCUSSÃO", url: "LINK_AQUI" }, { titulo: "AULA 03 - INSTRUMENTOS MELODICOS", url: "LINK_AQUI" }, { titulo: "AULA 04 - INSTRUMENTOS HARMONICOS", url: "LINK_AQUI" }] },
                { nome: "05. CRIAÇÃO DE RITMOS DE INSTRUMENTOS DE PERCUSSÃO", aulas: [{ titulo: "AULA 01 – INSTRUMENTOS DE PERCUSSÃO USADO NO AFRO HOUSE", url: "LINK_AQUI" }, { titulo: "AULA 02 – COMO CRIAR A BATERIA BASE DE AFRO HOUSE", url: "LINK_AQUI" }, { titulo: "AULA 03 – COMO CRIAR A PERCUSSÃO DO LONEKE", url: "LINK_AQUI" }, { titulo: "AULA 04 – COMO CRIAR A PERCUSSÃO DO TEO NO BEAT", url: "LINK_AQUI" }, { titulo: "AULA 05 – COMO CRIAR A PERCUSSÃO DO DJ MIKE", url: "LINK_AQUI" }, { titulo: "AULA 06 – COMO CRIAR A PERCUSSÃO DO TIA MARIA PRODUÇÃO", url: "LINK_AQUI" }, { titulo: "AULA 07 – COMO CRIAR A PERCUSSÃO DO DJ HABIAS", url: "LINK_AQUI" }, { titulo: "AULA 08 - CRIAÇÃO DE BREAKS OU TRANSIÇÕES", url: "LINK_AQUI" }, { titulo: "AULA 09 – COMO USAR BREAKS JÁ PRONTOS", url: "LINK_AQUI" }] },
                { nome: "06. CRIAÇÃO DE MELODIAS E HARMONIA", aulas: [{ titulo: "AULA 01 – VSTI E TIMBRES USADOS NA HORA DE CRIAR MELODIA PARA AFRO HOUSE", url: "LINK_AQUI" }, { titulo: "AULA 02 – TEORIA MUSICAL USADA NA CRIAÇÃO DE MELODIA DE AFRO HOUSE", url: "LINK_AQUI" }, { titulo: "AULA 03 – COMO CRIAR MELODIAS PARA AFRO HOUSE", url: "LINK_AQUI" }, { titulo: "AULA 04 – COMO CRIAR MELODIAS DE RESPOSTA", url: "LINK_AQUI" }, { titulo: "AULA 05 – COMO CRIAR MELODIAS USANDO LEAD E O BRASS", url: "LINK_AQUI" }] },
                { nome: "07. PRODUÇÃO DE BEATS & ESTRUTURAÇÃO (PRÁTICA)", aulas: [{ titulo: "AULA 01 – CRIANDO O BEAT 01", url: "LINK_AQUI" }, { titulo: "AULA 02 - ESTRUTURAR O BEAT 01", url: "LINK_AQUI" }, { titulo: "AULA 01 – CRIANDO O BEAT 02", url: "LINK_AQUI" }, { titulo: "AULA 02 - ESTRUTURAR O BEAT 02", url: "LINK_AQUI" }, { titulo: "AULA 01 – CRIANDO O BEAT 03", url: "LINK_AQUI" }, { titulo: "AULA 02 - ESTRUTURAR O BEAT 03", url: "LINK_AQUI" }] },
                { nome: "08. A BASE DA MIX E MASTER", aulas: [{ titulo: "AULA 01 - O QUE É MIX E MASTER", url: "LINK_AQUI" }, { titulo: "AULA 02 - BALANÇO TONAL E ANALISADOR DE ESPECTRO", url: "LINK_AQUI" }, { titulo: "AULA 03 - CRIAÇÃO DE GRUPOS", url: "LINK_AQUI" }, { titulo: "AULA 04 - EQUALIZAÇÃO (O QUE É, OS TIPOS DE EQUALIZAÇÃO, OS TIPOS DE FILTROS, OS TIPOS DE EQUALIZADORES)", url: "LINK_AQUI" }, { titulo: "AULA 05 - AS FREQUENCIAS E O PAPEL DE CADA REGIÃO", url: "LINK_AQUI" }, { titulo: "AULA 06 - COMPRESSOR (O QUE É, OS TIPOS DE COMPRESSOR, OS PARAMETROS)", url: "LINK_AQUI" }, { titulo: "AULA 07 - PRE AMPLIFICADORES", url: "LINK_AQUI" }, { titulo: "AULA 08 - SATURADORES", url: "LINK_AQUI" }, { titulo: "AULA 09 - EFEITOS (DELAY E REVERB)", url: "LINK_AQUI" }, { titulo: "AULA 10 - AUTO TUNE (CORRETOR DE NOTAS)", url: "LINK_AQUI" }, { titulo: "AULA 12 - AUTOMAÇÃO", url: "LINK_AQUI" }, { titulo: "AULA 12 - LIMITER E CLIPPER", url: "LINK_AQUI" }, { titulo: "AULA 13 - SIDE CHAN", url: "LINK_AQUI" }, { titulo: "AULA 14 - IMAGEM STEREO", url: "LINK_AQUI" }] },
                { nome: "09. MIX E MASTER (PRATICA)", aulas: [{ titulo: "AULA 01 - EXPORTAR OS STEAM DE UM BEAT/PROJECTO", url: "LINK_AQUI" }, { titulo: "AULA 02 - ORGANIZAR O PROJECTO PARA MIX E MASTER", url: "LINK_AQUI" }, { titulo: "AULA 03 - MIXAR O PRIMEIRO BEAT DO PRINCIPIO ATÉ AO FIM ", url: "LINK_AQUI" }, { titulo: "AULA 04 – COMO MASTERIZAR O PRIMEIRO BEAT", url: "LINK_AQUI" }, { titulo: "AULA 05- MIXAR O SEGUNDO BEAT DO PRINCIPIO ATÉ AO FIM ", url: "LINK_AQUI" }, { titulo: "AULA 06 – COMO MASTERIZAR O SEGUNDO BEAT", url: "LINK_AQUI" }] }
            ]
        },
        {
            id: 5,
            titulo: "CURSO COMPLETO DE PRODUÇÃO DE DRILL + MIX E MASTER NO FL STUDIO",
            imagem: "../img/prontos/",
            desbloqueado: false,
            linkMaterial: "https://mediafire.com/exemplo",
            modulos: [
                { nome: "01. COMECE AQUI", aulas: [{ titulo: "OBRIGADO", url: "LINK_AQUI" }, { titulo: "COMO VAI FUNCIONAR O CURSO E COMO BAIXAR OS PLUGINS USADOS NA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "A BASE DA PRODUÇÃO MUSICAL E EQUIPAMENTOS PARA A NOSSA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "CONCEITOS BÁSICOS SOBRE PRODUÇÃO MUSICAL", url: "LINK_AQUI" }, { titulo: "VST E VSTI", url: "LINK_AQUI" }, { titulo: "INSTALANDO OS PROGRAMA DA FORMAÇÃO", url: "LINK_AQUI" }] },
                { nome: "02. A BASE DA PRODUÇÃO MUSICAL (FL STUDIO O BÁSICO)", aulas: [{ titulo: "AULA 01 - APRESENTAÇÃO DO AMBIENTE DO FL STUDIO", url: "https://youtu.be/tcZboMaPw5c" }, { titulo: "AULA 02 - BOTÕES DE PLAY, STOP E RECORD", url: "https://youtu.be/S9cEhJMundI" }, { titulo: "AULA 03 - CHANNEL RACK", url: "https://youtu.be/PjSxV4ol6MM" }, { titulo: "AULA 04 - PIANO ROLL", url: "https://youtu.be/O8wzgTuchL8" }, { titulo: "AULA 05 - BROWSER", url: "https://youtu.be/pmUOj8FnIJs" }, { titulo: "AULA 06 - MENU", url: "https://youtu.be/c0crY-l7lBw" }, { titulo: "AULA 07 - PLAYLIST", url: "https://youtu.be/ZtYalbddMsc" }, { titulo: "AULA 08 - MIXER", url: "https://youtu.be/LAwVXwlkSbY" }, { titulo: "AULA 09 - COMO CONFIGURAR O FL STUDIO", url: "https://youtu.be/ps9Rg_XP-wU" }, { titulo: "AULA 10 - COMO ADICIONAR OS DRUMKITS DENTRO DO FL STUDIO", url: "https://youtu.be/Qr5umV3H9qI" }, { titulo: "AULA 11 - COMO SCANNEAR PLUGINS DENTRO DO FL STUDIO", url: "https://youtu.be/zUg5QchOBvM" }, { titulo: "AULA 12 - COMO GRAVAR UMA VOZ NO FL STUDIO", url: "https://youtu.be/T1-6w7Ok25o" }, { titulo: "AULA 13 - COMO REMOVER RUIDO DE UMA VOZ NO FL STUDIO", url: "https://youtu.be/pqYrZIS24Do" }, { titulo: "AULA 14 - ATALHOS NO FL STUDIO", url: "https://youtu.be/hE3CsImmPrU" }, { titulo: "AULA 15 - GRID E COMPASSOS", url: "https://youtu.be/f3yMkzRfYGA" }, { titulo: "AULA 16 - COMO ACHAR O BPM DE UMA MÚSICA", url: "https://youtu.be/QfJU7BCYi4I" }, { titulo: "AULA 17 - COMO COLOCAR QUALQUER AUDIO DENTRO DA NOTA ( VOCAL, ONE SHOT E 808 )", url: "https://youtu.be/R3xZKrng9g4" }, { titulo: "AULA 18 - COMO SEPARAR AS PARTES DE UMA MÚSICA", url: "https://youtu.be/vJcW794o5DY" }, { titulo: "AULA 19 - CHANNEL RACK AVANÇADO", url: "https://youtu.be/MFrCKJ6MLL8" }, { titulo: "AULA 20 - COMO LIGAR O CONTROLADOR MIDI", url: "https://youtu.be/4DIH2kTgP9Q" }] },
                { nome: "03. A BASE DA TEORIA MUSICAL", aulas: [{ titulo: "AULA 01 - TEORIA MUSICAL", url: "https://youtu.be/BMV2nPGwU70" }, { titulo: "AULA 02 - NOTAS MUSICAS E NOTAS DE ACIDENTE", url: "https://youtu.be/_-XMBkyz77w" }, { titulo: "AULA 03 - CIFRAS", url: "https://youtu.be/LgDAech2LiU" }, { titulo: "AULA 04 - INTERVALOS", url: "https://youtu.be/Ok-PTt11S7g" }, { titulo: "AULA 05 - ESCALAS", url: "https://youtu.be/xApa3-95rT8" }, { titulo: "AULA 06 - FORMAÇÃO DE ESCALAS", url: "https://youtu.be/JLoNI6bFkJs" }, { titulo: "AULA 07 - ACORDES", url: "https://youtu.be/TVVHJlC-BQk" }, { titulo: "AULA 08 - CRIAÇÃO DE ACORDES", url: "https://youtu.be/QL9_zGlgyYg" }, { titulo: "AULA 09 - CAMPO HARMONICO", url: "https://youtu.be/RK7s8dSHkkU" }, { titulo: "AULA 10 - CRIANDO PROGRESSÕES DE ACORDE COM CAMPO HARMONICO", url: "https://youtu.be/MqyH_WydNfg" }, { titulo: "AULA 11 - CRIAR PROGRESSÕES DE ACORDE COM APENAS UM CLIQUE", url: "https://youtu.be/n6wvtMqNGqw" }, { titulo: "AULA 12 - COMO TIRAR AS CIFRAS DE UMA MÚSICA", url: "https://youtu.be/sLevV4Je4Gk" }, { titulo: "AULA 13 - CRIANDO PROGRESSÕES DE ACORDE COM O SCALLER", url: "https://youtu.be/OVeRVWw410E" }, { titulo: "AULA 14 - SITE PARA ENCONTRAR CIFRAS DE UMA MÚSICA", url: "https://youtu.be/37qMcwzOjyU" }, { titulo: "AULA 15 - COMO COPIAR OU ROUBAR MELODIAS DE OUTRAS MÚSICAS", url: "https://youtu.be/0f-ox5FjOdg" }, { titulo: "AULA 16 - COMO ACHAR A NOTA OU ESCALA DE UM BEAT", url: "https://youtu.be/uNxZ5FU-q-g" }] },
                { nome: "04. TIMBRES", aulas: [{ titulo: "AULA 01 - O QUE É UM TIMBRE E O SEU PAPEL E OS TIPOS DE INSTRUMENTOS", url: "LINK_AQUI" }, { titulo: "AULA 02 - INSTRUMENTOS DE PERCUSSÃO", url: "LINK_AQUI" }, { titulo: "AULA 03 - INSTRUMENTOS MELODICOS", url: "LINK_AQUI" }, { titulo: "AULA 04 - INSTRUMENTOS HARMONICOS", url: "LINK_AQUI" }] },
                { nome: "05. CRIAÇÃO DE RITMOS DE INSTRUMENTOS DE PERCUSSÃO", aulas: [{ titulo: "AULA 01", url: "LINK_AQUI" }, { titulo: "AULA 02", url: "LINK_AQUI" }, { titulo: "AULA 03", url: "LINK_AQUI" }, { titulo: "AULA 04", url: "LINK_AQUI" }] },
                { nome: "06. CRIAÇÃO DE MELODIAS E HARMONIA", aulas: [{ titulo: "AULA 01", url: "LINK_AQUI" }, { titulo: "AULA 02", url: "LINK_AQUI" }, { titulo: "AULA 03", url: "LINK_AQUI" }, { titulo: "AULA 04", url: "LINK_AQUI" }] },
                { nome: "07. PRODUÇÃO DE BEATS & ESTRUTURAÇÃO (PRÁTICA)", aulas: [{ titulo: "AULA 01 – CRIANDO O BEAT 01", url: "LINK_AQUI" }, { titulo: "AULA 02 - ESTRUTURAR O BEAT 01", url: "LINK_AQUI" }, { titulo: "AULA 01 – CRIANDO O BEAT 02", url: "LINK_AQUI" }, { titulo: "AULA 02 - ESTRUTURAR O BEAT 02", url: "LINK_AQUI" }, { titulo: "AULA 01 – CRIANDO O BEAT 03", url: "LINK_AQUI" }, { titulo: "AULA 02 - ESTRUTURAR O BEAT 03", url: "LINK_AQUI" }] },
                { nome: "08. A BASE DA MIX E MASTER", aulas: [{ titulo: "AULA 01 - O QUE É MIX E MASTER", url: "LINK_AQUI" }, { titulo: "AULA 02 - BALANÇO TONAL E ANALISADOR DE ESPECTRO", url: "LINK_AQUI" }, { titulo: "AULA 03 - CRIAÇÃO DE GRUPOS", url: "LINK_AQUI" }, { titulo: "AULA 04 - EQUALIZAÇÃO (O QUE É, OS TIPOS DE EQUALIZAÇÃO, OS TIPOS DE FILTROS, OS TIPOS DE EQUALIZADORES)", url: "LINK_AQUI" }, { titulo: "AULA 05 - AS FREQUENCIAS E O PAPEL DE CADA REGIÃO", url: "LINK_AQUI" }, { titulo: "AULA 06 - COMPRESSOR (O QUE É, OS TIPOS DE COMPRESSOR, OS PARAMETROS)", url: "LINK_AQUI" }, { titulo: "AULA 07 - PRE AMPLIFICADORES", url: "LINK_AQUI" }, { titulo: "AULA 08 - SATURADORES", url: "LINK_AQUI" }, { titulo: "AULA 09 - EFEITOS (DELAY E REVERB)", url: "LINK_AQUI" }, { titulo: "AULA 10 - AUTO TUNE (CORRETOR DE NOTAS)", url: "LINK_AQUI" }, { titulo: "AULA 12 - AUTOMAÇÃO", url: "LINK_AQUI" }, { titulo: "AULA 12 - LIMITER E CLIPPER", url: "LINK_AQUI" }, { titulo: "AULA 13 - SIDE CHAN", url: "LINK_AQUI" }, { titulo: "AULA 14 - IMAGEM STEREO", url: "LINK_AQUI" }] },
                { nome: "09. MIX E MASTER (PRATICA)", aulas: [{ titulo: "AULA 01 - EXPORTAR OS STEAM DE UM BEAT/PROJECTO", url: "LINK_AQUI" }, { titulo: "AULA 02 - ORGANIZAR O PROJECTO PARA MIX E MASTER", url: "LINK_AQUI" }, { titulo: "AULA 03 - MIXAR O PRIMEIRO BEAT DO PRINCIPIO ATÉ AO FIM ", url: "LINK_AQUI" }, { titulo: "AULA 04 – COMO MASTERIZAR O PRIMEIRO BEAT", url: "LINK_AQUI" }, { titulo: "AULA 05- MIXAR O SEGUNDO BEAT DO PRINCIPIO ATÉ AO FIM ", url: "LINK_AQUI" }, { titulo: "AULA 06 – COMO MASTERIZAR O SEGUNDO BEAT", url: "LINK_AQUI" }] }
            ]
        },
        {
            id: 6,
            titulo: "CURSO COMPLETO DE PRODUÇÃO DE GUETHO ZOUK + MIX E MASTER NO FL STUDIO",
            imagem: "../img/prontos/CURSO DE PRODUÇÃO DE BEATS DE GUETHO ZOUK DE ANGOLA MIX E MASTER NO FL STUDIO.jpg",
            desbloqueado: false,
            linkMaterial: "https://mediafire.com/exemplo",
            modulos: [
                { nome: "01. COMECE AQUI", aulas: [{ titulo: "OBRIGADO", url: "LINK_AQUI" }, { titulo: "COMO VAI FUNCIONAR O CURSO E COMO BAIXAR OS PLUGINS USADOS NA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "A BASE DA PRODUÇÃO MUSICAL E EQUIPAMENTOS PARA A NOSSA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "CONCEITOS BÁSICOS SOBRE PRODUÇÃO MUSICAL", url: "LINK_AQUI" }, { titulo: "VST E VSTI", url: "LINK_AQUI" }, { titulo: "INSTALANDO OS PROGRAMA DA FORMAÇÃO", url: "LINK_AQUI" }] },
                { nome: "02. A BASE DA PRODUÇÃO MUSICAL (FL STUDIO O BÁSICO)", aulas: [{ titulo: "AULA 01 - APRESENTAÇÃO DO AMBIENTE DO FL STUDIO", url: "https://youtu.be/tcZboMaPw5c" }, { titulo: "AULA 02 - BOTÕES DE PLAY, STOP E RECORD", url: "https://youtu.be/S9cEhJMundI" }, { titulo: "AULA 03 - CHANNEL RACK", url: "https://youtu.be/PjSxV4ol6MM" }, { titulo: "AULA 04 - PIANO ROLL", url: "https://youtu.be/O8wzgTuchL8" }, { titulo: "AULA 05 - BROWSER", url: "https://youtu.be/pmUOj8FnIJs" }, { titulo: "AULA 06 - MENU", url: "https://youtu.be/c0crY-l7lBw" }, { titulo: "AULA 07 - PLAYLIST", url: "https://youtu.be/ZtYalbddMsc" }, { titulo: "AULA 08 - MIXER", url: "https://youtu.be/LAwVXwlkSbY" }, { titulo: "AULA 09 - COMO CONFIGURAR O FL STUDIO", url: "https://youtu.be/ps9Rg_XP-wU" }, { titulo: "AULA 10 - COMO ADICIONAR OS DRUMKITS DENTRO DO FL STUDIO", url: "https://youtu.be/Qr5umV3H9qI" }, { titulo: "AULA 11 - COMO SCANNEAR PLUGINS DENTRO DO FL STUDIO", url: "https://youtu.be/zUg5QchOBvM" }, { titulo: "AULA 12 - COMO GRAVAR UMA VOZ NO FL STUDIO", url: "https://youtu.be/T1-6w7Ok25o" }, { titulo: "AULA 13 - COMO REMOVER RUIDO DE UMA VOZ NO FL STUDIO", url: "https://youtu.be/pqYrZIS24Do" }, { titulo: "AULA 14 - ATALHOS NO FL STUDIO", url: "https://youtu.be/hE3CsImmPrU" }, { titulo: "AULA 15 - GRID E COMPASSOS", url: "https://youtu.be/f3yMkzRfYGA" }, { titulo: "AULA 16 - COMO ACHAR O BPM DE UMA MÚSICA", url: "https://youtu.be/QfJU7BCYi4I" }, { titulo: "AULA 17 - COMO COLOCAR QUALQUER AUDIO DENTRO DA NOTA ( VOCAL, ONE SHOT E 808 )", url: "https://youtu.be/R3xZKrng9g4" }, { titulo: "AULA 18 - COMO SEPARAR AS PARTES DE UMA MÚSICA", url: "https://youtu.be/vJcW794o5DY" }, { titulo: "AULA 19 - CHANNEL RACK AVANÇADO", url: "https://youtu.be/MFrCKJ6MLL8" }, { titulo: "AULA 20 - COMO LIGAR O CONTROLADOR MIDI", url: "https://youtu.be/4DIH2kTgP9Q" }] },
                { nome: "03. A BASE DA TEORIA MUSICAL", aulas: [{ titulo: "AULA 01 - TEORIA MUSICAL", url: "https://youtu.be/BMV2nPGwU70" }, { titulo: "AULA 02 - NOTAS MUSICAS E NOTAS DE ACIDENTE", url: "https://youtu.be/_-XMBkyz77w" }, { titulo: "AULA 03 - CIFRAS", url: "https://youtu.be/LgDAech2LiU" }, { titulo: "AULA 04 - INTERVALOS", url: "https://youtu.be/Ok-PTt11S7g" }, { titulo: "AULA 05 - ESCALAS", url: "https://youtu.be/xApa3-95rT8" }, { titulo: "AULA 06 - FORMAÇÃO DE ESCALAS", url: "https://youtu.be/JLoNI6bFkJs" }, { titulo: "AULA 07 - ACORDES", url: "https://youtu.be/TVVHJlC-BQk" }, { titulo: "AULA 08 - CRIAÇÃO DE ACORDES", url: "https://youtu.be/QL9_zGlgyYg" }, { titulo: "AULA 09 - CAMPO HARMONICO", url: "https://youtu.be/RK7s8dSHkkU" }, { titulo: "AULA 10 - CRIANDO PROGRESSÕES DE ACORDE COM CAMPO HARMONICO", url: "https://youtu.be/MqyH_WydNfg" }, { titulo: "AULA 11 - CRIAR PROGRESSÕES DE ACORDE COM APENAS UM CLIQUE", url: "https://youtu.be/n6wvtMqNGqw" }, { titulo: "AULA 12 - COMO TIRAR AS CIFRAS DE UMA MÚSICA", url: "https://youtu.be/sLevV4Je4Gk" }, { titulo: "AULA 13 - CRIANDO PROGRESSÕES DE ACORDE COM O SCALLER", url: "https://youtu.be/OVeRVWw410E" }, { titulo: "AULA 14 - SITE PARA ENCONTRAR CIFRAS DE UMA MÚSICA", url: "https://youtu.be/37qMcwzOjyU" }, { titulo: "AULA 15 - COMO COPIAR OU ROUBAR MELODIAS DE OUTRAS MÚSICAS", url: "https://youtu.be/0f-ox5FjOdg" }, { titulo: "AULA 16 - COMO ACHAR A NOTA OU ESCALA DE UM BEAT", url: "https://youtu.be/uNxZ5FU-q-g" }] },
                { nome: "04. TIMBRES", aulas: [{ titulo: "AULA 01 - O QUE É UM TIMBRE E O SEU PAPEL E OS TIPOS DE INSTRUMENTOS", url: "LINK_AQUI" }, { titulo: "AULA 02 - INSTRUMENTOS DE PERCUSSÃO", url: "LINK_AQUI" }, { titulo: "AULA 03 - INSTRUMENTOS MELODICOS", url: "LINK_AQUI" }, { titulo: "AULA 04 - INSTRUMENTOS HARMONICOS", url: "LINK_AQUI" }] },
                { nome: "05. CRIAÇÃO DE RITMOS DE INSTRUMENTOS DE PERCUSSÃO", aulas: [{ titulo: "AULA 01 – INSTRUMENTOS DE PERCUSSÃO USADO NO GUETHO ZOUK", url: "LINK_AQUI" }, { titulo: "AULA 02 – COMO CRIAR A BATERIA BASE DE GUETHO ZOUK", url: "LINK_AQUI" }, { titulo: "AULA 03 – COMO CRIAR A BATERIA DO PRE CABUNDA COME PÃO", url: "LINK_AQUI" }, { titulo: "AULA 04 – COMO CRIAR A PERCUSSÃO DO GUETHO ZOUK", url: "LINK_AQUI" }, { titulo: "AULA 05 – COMO CRIAR A BATERIA + PERCUSSÃO ", url: "LINK_AQUI" }, { titulo: "AULA 06 - CRIAÇÃO DE BREAKS OU TRANSIÇÕES", url: "LINK_AQUI" }, { titulo: "AULA 07 – COMO USAR BREAKS EM FORMATO DE AUDIO", url: "LINK_AQUI" }] },
                { nome: "06. CRIAÇÃO DE MELODIAS E HARMONIA", aulas: [{ titulo: "AULA 01 – VSTI E TIMBRES USADOS NA HORA DE CRIAR MELODIA PARA GUETHO ZOUK", url: "LINK_AQUI" }, { titulo: "AULA 02 – TEORIA MUSICAL USADA NA CRIAÇÃO DE MELODIA DE GUETHO ZOUK", url: "LINK_AQUI" }, { titulo: "AULA 03 – COMO CRIAR BOAS PROGRESSÕES DE ACORDE PARA GUETHO ZOUK", url: "LINK_AQUI" }, { titulo: "AULA 04 – COMO TOCAR O PAD", url: "LINK_AQUI" }, { titulo: "AULA 05 – COMO TOCAR O ARPEJO", url: "LINK_AQUI" }, { titulo: "AULA 06 – COMO TOCAR O BAIXO", url: "LINK_AQUI" }, { titulo: "AULA 07 – COMO CRIAR MELODIAS PARA GUETHO ZOUK  USANDO BELL/LEAD", url: "LINK_AQUI" }, { titulo: "AULA 08 – COMO CRIAR MELODIAS PARA GUETHO ZOUK USANDO PIANO", url: "LINK_AQUI" }, { titulo: "AULA 09 – COMO CRIAR MELODIAS DE GUETHO ZOUK 2", url: "LINK_AQUI" }, { titulo: "AULA 10 – COMO CRIAR MELODIAS DE GUETHO ZOUK 3", url: "LINK_AQUI" }] },
                { nome: "07. PRODUÇÃO DE BEATS & ESTRUTURAÇÃO (PRÁTICA)", aulas: [{ titulo: "AULA 01 – CRIANDO O BEAT 01", url: "LINK_AQUI" }, { titulo: "AULA 02 - ESTRUTURAR O BEAT 01", url: "LINK_AQUI" }, { titulo: "AULA 01 – CRIANDO O BEAT 02", url: "LINK_AQUI" }, { titulo: "AULA 02 - ESTRUTURAR O BEAT 02", url: "LINK_AQUI" }, { titulo: "AULA 01 – CRIANDO O BEAT 03", url: "LINK_AQUI" }, { titulo: "AULA 02 - ESTRUTURAR O BEAT 03", url: "LINK_AQUI" }] },
                { nome: "08. A BASE DA MIX E MASTER", aulas: [{ titulo: "AULA 01 - O QUE É MIX E MASTER", url: "LINK_AQUI" }, { titulo: "AULA 02 - BALANÇO TONAL E ANALISADOR DE ESPECTRO", url: "LINK_AQUI" }, { titulo: "AULA 03 - CRIAÇÃO DE GRUPOS", url: "LINK_AQUI" }, { titulo: "AULA 04 - EQUALIZAÇÃO (O QUE É, OS TIPOS DE EQUALIZAÇÃO, OS TIPOS DE FILTROS, OS TIPOS DE EQUALIZADORES)", url: "LINK_AQUI" }, { titulo: "AULA 05 - AS FREQUENCIAS E O PAPEL DE CADA REGIÃO", url: "LINK_AQUI" }, { titulo: "AULA 06 - COMPRESSOR (O QUE É, OS TIPOS DE COMPRESSOR, OS PARAMETROS)", url: "LINK_AQUI" }, { titulo: "AULA 07 - PRE AMPLIFICADORES", url: "LINK_AQUI" }, { titulo: "AULA 08 - SATURADORES", url: "LINK_AQUI" }, { titulo: "AULA 09 - EFEITOS (DELAY E REVERB)", url: "LINK_AQUI" }, { titulo: "AULA 10 - AUTO TUNE (CORRETOR DE NOTAS)", url: "LINK_AQUI" }, { titulo: "AULA 12 - AUTOMAÇÃO", url: "LINK_AQUI" }, { titulo: "AULA 12 - LIMITER E CLIPPER", url: "LINK_AQUI" }, { titulo: "AULA 13 - SIDE CHAN", url: "LINK_AQUI" }, { titulo: "AULA 14 - IMAGEM STEREO", url: "LINK_AQUI" }] },
                { nome: "09. MIX E MASTER (PRATICA)", aulas: [{ titulo: "AULA 01 - EXPORTAR OS STEAM DE UM BEAT/PROJECTO", url: "LINK_AQUI" }, { titulo: "AULA 02 - ORGANIZAR O PROJECTO PARA MIX E MASTER", url: "LINK_AQUI" }, { titulo: "AULA 03 - MIXAR O PRIMEIRO BEAT DO PRINCIPIO ATÉ AO FIM ", url: "LINK_AQUI" }, { titulo: "AULA 04 – COMO MASTERIZAR O PRIMEIRO BEAT", url: "LINK_AQUI" }, { titulo: "AULA 05- MIXAR O SEGUNDO BEAT DO PRINCIPIO ATÉ AO FIM ", url: "LINK_AQUI" }, { titulo: "AULA 06 – COMO MASTERIZAR O SEGUNDO BEAT", url: "LINK_AQUI" }] }
            ]
        },
        {
            id: 7,
            titulo: "CURSO COMPLETO DE PRODUÇÃO DE KOMPA + MIX E MASTER NO FL STUDIO",
            imagem: "../img/prontos/",
            desbloqueado: false,
            linkMaterial: "https://mediafire.com/exemplo",
            modulos: [
                { nome: "01. COMECE AQUI", aulas: [{ titulo: "OBRIGADO", url: "LINK_AQUI" }, { titulo: "COMO VAI FUNCIONAR O CURSO E COMO BAIXAR OS PLUGINS USADOS NA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "A BASE DA PRODUÇÃO MUSICAL E EQUIPAMENTOS PARA A NOSSA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "CONCEITOS BÁSICOS SOBRE PRODUÇÃO MUSICAL", url: "LINK_AQUI" }, { titulo: "VST E VSTI", url: "LINK_AQUI" }, { titulo: "INSTALANDO OS PROGRAMA DA FORMAÇÃO", url: "LINK_AQUI" }] },
                { nome: "02. A BASE DA PRODUÇÃO MUSICAL (FL STUDIO O BÁSICO)", aulas: [{ titulo: "AULA 01 - APRESENTAÇÃO DO AMBIENTE DO FL STUDIO", url: "https://youtu.be/tcZboMaPw5c" }, { titulo: "AULA 02 - BOTÕES DE PLAY, STOP E RECORD", url: "https://youtu.be/S9cEhJMundI" }, { titulo: "AULA 03 - CHANNEL RACK", url: "https://youtu.be/PjSxV4ol6MM" }, { titulo: "AULA 04 - PIANO ROLL", url: "https://youtu.be/O8wzgTuchL8" }, { titulo: "AULA 05 - BROWSER", url: "https://youtu.be/pmUOj8FnIJs" }, { titulo: "AULA 06 - MENU", url: "https://youtu.be/c0crY-l7lBw" }, { titulo: "AULA 07 - PLAYLIST", url: "https://youtu.be/ZtYalbddMsc" }, { titulo: "AULA 08 - MIXER", url: "https://youtu.be/LAwVXwlkSbY" }, { titulo: "AULA 09 - COMO CONFIGURAR O FL STUDIO", url: "https://youtu.be/ps9Rg_XP-wU" }, { titulo: "AULA 10 - COMO ADICIONAR OS DRUMKITS DENTRO DO FL STUDIO", url: "https://youtu.be/Qr5umV3H9qI" }, { titulo: "AULA 11 - COMO SCANNEAR PLUGINS DENTRO DO FL STUDIO", url: "https://youtu.be/zUg5QchOBvM" }, { titulo: "AULA 12 - COMO GRAVAR UMA VOZ NO FL STUDIO", url: "https://youtu.be/T1-6w7Ok25o" }, { titulo: "AULA 13 - COMO REMOVER RUIDO DE UMA VOZ NO FL STUDIO", url: "https://youtu.be/pqYrZIS24Do" }, { titulo: "AULA 14 - ATALHOS NO FL STUDIO", url: "https://youtu.be/hE3CsImmPrU" }, { titulo: "AULA 15 - GRID E COMPASSOS", url: "https://youtu.be/f3yMkzRfYGA" }, { titulo: "AULA 16 - COMO ACHAR O BPM DE UMA MÚSICA", url: "https://youtu.be/QfJU7BCYi4I" }, { titulo: "AULA 17 - COMO COLOCAR QUALQUER AUDIO DENTRO DA NOTA ( VOCAL, ONE SHOT E 808 )", url: "https://youtu.be/R3xZKrng9g4" }, { titulo: "AULA 18 - COMO SEPARAR AS PARTES DE UMA MÚSICA", url: "https://youtu.be/vJcW794o5DY" }, { titulo: "AULA 19 - CHANNEL RACK AVANÇADO", url: "https://youtu.be/MFrCKJ6MLL8" }, { titulo: "AULA 20 - COMO LIGAR O CONTROLADOR MIDI", url: "https://youtu.be/4DIH2kTgP9Q" }] },
                { nome: "03. A BASE DA TEORIA MUSICAL", aulas: [{ titulo: "AULA 01 - TEORIA MUSICAL", url: "https://youtu.be/BMV2nPGwU70" }, { titulo: "AULA 02 - NOTAS MUSICAS E NOTAS DE ACIDENTE", url: "https://youtu.be/_-XMBkyz77w" }, { titulo: "AULA 03 - CIFRAS", url: "https://youtu.be/LgDAech2LiU" }, { titulo: "AULA 04 - INTERVALOS", url: "https://youtu.be/Ok-PTt11S7g" }, { titulo: "AULA 05 - ESCALAS", url: "https://youtu.be/xApa3-95rT8" }, { titulo: "AULA 06 - FORMAÇÃO DE ESCALAS", url: "https://youtu.be/JLoNI6bFkJs" }, { titulo: "AULA 07 - ACORDES", url: "https://youtu.be/TVVHJlC-BQk" }, { titulo: "AULA 08 - CRIAÇÃO DE ACORDES", url: "https://youtu.be/QL9_zGlgyYg" }, { titulo: "AULA 09 - CAMPO HARMONICO", url: "https://youtu.be/RK7s8dSHkkU" }, { titulo: "AULA 10 - CRIANDO PROGRESSÕES DE ACORDE COM CAMPO HARMONICO", url: "https://youtu.be/MqyH_WydNfg" }, { titulo: "AULA 11 - CRIAR PROGRESSÕES DE ACORDE COM APENAS UM CLIQUE", url: "https://youtu.be/n6wvtMqNGqw" }, { titulo: "AULA 12 - COMO TIRAR AS CIFRAS DE UMA MÚSICA", url: "https://youtu.be/sLevV4Je4Gk" }, { titulo: "AULA 13 - CRIANDO PROGRESSÕES DE ACORDE COM O SCALLER", url: "https://youtu.be/OVeRVWw410E" }, { titulo: "AULA 14 - SITE PARA ENCONTRAR CIFRAS DE UMA MÚSICA", url: "https://youtu.be/37qMcwzOjyU" }, { titulo: "AULA 15 - COMO COPIAR OU ROUBAR MELODIAS DE OUTRAS MÚSICAS", url: "https://youtu.be/0f-ox5FjOdg" }, { titulo: "AULA 16 - COMO ACHAR A NOTA OU ESCALA DE UM BEAT", url: "https://youtu.be/uNxZ5FU-q-g" }] },
                { nome: "04. TIMBRES", aulas: [{ titulo: "AULA 01 - O QUE É UM TIMBRE E O SEU PAPEL E OS TIPOS DE INSTRUMENTOS", url: "LINK_AQUI" }, { titulo: "AULA 02 - INSTRUMENTOS DE PERCUSSÃO", url: "LINK_AQUI" }, { titulo: "AULA 03 - INSTRUMENTOS MELODICOS", url: "LINK_AQUI" }, { titulo: "AULA 04 - INSTRUMENTOS HARMONICOS", url: "LINK_AQUI" }] },
                { nome: "05. CRIAÇÃO DE RITMOS DE INSTRUMENTOS DE PERCUSSÃO", aulas: [{ titulo: "AULA 1", url: "LINK_AQUI" }, { titulo: "AULA 2", url: "LINK_AQUI" }, { titulo: "AULA 3", url: "LINK_AQUI" }] },
                { nome: "06. CRIAÇÃO DE MELODIAS E HARMONIA", aulas: [{ titulo: "AULA 01", url: "LINK_AQUI" }, { titulo: "AULA 02", url: "LINK_AQUI" }, { titulo: "AULA 03", url: "LINK_AQUI" }] },
                { nome: "07. PRODUÇÃO DE BEATS & ESTRUTURAÇÃO (PRÁTICA)", aulas: [{ titulo: "AULA 01 – CRIANDO O BEAT 01", url: "LINK_AQUI" }, { titulo: "AULA 02 - ESTRUTURAR O BEAT 01", url: "LINK_AQUI" }, { titulo: "AULA 03 – CRIANDO O BEAT 02", url: "LINK_AQUI" }, { titulo: "AULA 04 - ESTRUTURAR O BEAT 02", url: "LINK_AQUI" }, { titulo: "AULA 05 – CRIANDO O BEAT 03", url: "LINK_AQUI" }, { titulo: "AULA 06 - ESTRUTURAR O BEAT 03", url: "LINK_AQUI" }] },
                { nome: "08. A BASE DA MIX E MASTER", aulas: [{ titulo: "AULA 01 - O QUE É MIX E MASTER", url: "LINK_AQUI" }, { titulo: "AULA 02 - BALANÇO TONAL E ANALISADOR DE ESPECTRO", url: "LINK_AQUI" }, { titulo: "AULA 03 - CRIAÇÃO DE GRUPOS", url: "LINK_AQUI" }, { titulo: "AULA 04 - EQUALIZAÇÃO (O QUE É, OS TIPOS DE EQUALIZAÇÃO, OS TIPOS DE FILTROS, OS TIPOS DE EQUALIZADORES)", url: "LINK_AQUI" }, { titulo: "AULA 05 - AS FREQUENCIAS E O PAPEL DE CADA REGIÃO", url: "LINK_AQUI" }, { titulo: "AULA 06 - COMPRESSOR (O QUE É, OS TIPOS DE COMPRESSOR, OS PARAMETROS)", url: "LINK_AQUI" }, { titulo: "AULA 07 - PRE AMPLIFICADORES", url: "LINK_AQUI" }, { titulo: "AULA 08 - SATURADORES", url: "LINK_AQUI" }, { titulo: "AULA 09 - EFEITOS (DELAY E REVERB)", url: "LINK_AQUI" }, { titulo: "AULA 10 - AUTO TUNE (CORRETOR DE NOTAS)", url: "LINK_AQUI" }, { titulo: "AULA 12 - AUTOMAÇÃO", url: "LINK_AQUI" }, { titulo: "AULA 12 - LIMITER E CLIPPER", url: "LINK_AQUI" }, { titulo: "AULA 13 - SIDE CHAN", url: "LINK_AQUI" }, { titulo: "AULA 14 - IMAGEM STEREO", url: "LINK_AQUI" }] },
                { nome: "09. MIX E MASTER (PRATICA)", aulas: [{ titulo: "AULA 01 - EXPORTAR OS STEAM DE UM BEAT/PROJECTO", url: "LINK_AQUI" }, { titulo: "AULA 02 - ORGANIZAR O PROJECTO PARA MIX E MASTER", url: "LINK_AQUI" }, { titulo: "AULA 03 - MIXAR O PRIMEIRO BEAT DO PRINCIPIO ATÉ AO FIM ", url: "LINK_AQUI" }, { titulo: "AULA 04 – COMO MASTERIZAR O PRIMEIRO BEAT", url: "LINK_AQUI" }, { titulo: "AULA 05- MIXAR O SEGUNDO BEAT DO PRINCIPIO ATÉ AO FIM ", url: "LINK_AQUI" }, { titulo: "AULA 06 – COMO MASTERIZAR O SEGUNDO BEAT", url: "LINK_AQUI" }] }
            ]
        },
        {
            id: 8,
            titulo: "CURSO COMPLETO DE PRODUÇÃO DE KUDURO ADOÇO + MIX E MASTER NO FL STUDIO",
            imagem: "../img/prontos/",
            desbloqueado: false,
            linkMaterial: "https://mediafire.com/exemplo",
            modulos: [
                { nome: "01. COMECE AQUI", aulas: [{ titulo: "OBRIGADO", url: "LINK_AQUI" }, { titulo: "COMO VAI FUNCIONAR O CURSO E COMO BAIXAR OS PLUGINS USADOS NA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "A BASE DA PRODUÇÃO MUSICAL E EQUIPAMENTOS PARA A NOSSA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "CONCEITOS BÁSICOS SOBRE PRODUÇÃO MUSICAL", url: "LINK_AQUI" }, { titulo: "VST E VSTI", url: "LINK_AQUI" }, { titulo: "INSTALANDO OS PROGRAMA DA FORMAÇÃO", url: "LINK_AQUI" }] },
                { nome: "02. A BASE DA PRODUÇÃO MUSICAL (FL STUDIO O BÁSICO)", aulas: [{ titulo: "AULA 01 - APRESENTAÇÃO DO AMBIENTE DO FL STUDIO", url: "https://youtu.be/tcZboMaPw5c" }, { titulo: "AULA 02 - BOTÕES DE PLAY, STOP E RECORD", url: "https://youtu.be/S9cEhJMundI" }, { titulo: "AULA 03 - CHANNEL RACK", url: "https://youtu.be/PjSxV4ol6MM" }, { titulo: "AULA 04 - PIANO ROLL", url: "https://youtu.be/O8wzgTuchL8" }, { titulo: "AULA 05 - BROWSER", url: "https://youtu.be/pmUOj8FnIJs" }, { titulo: "AULA 06 - MENU", url: "https://youtu.be/c0crY-l7lBw" }, { titulo: "AULA 07 - PLAYLIST", url: "https://youtu.be/ZtYalbddMsc" }, { titulo: "AULA 08 - MIXER", url: "https://youtu.be/LAwVXwlkSbY" }, { titulo: "AULA 09 - COMO CONFIGURAR O FL STUDIO", url: "https://youtu.be/ps9Rg_XP-wU" }, { titulo: "AULA 10 - COMO ADICIONAR OS DRUMKITS DENTRO DO FL STUDIO", url: "https://youtu.be/Qr5umV3H9qI" }, { titulo: "AULA 11 - COMO SCANNEAR PLUGINS DENTRO DO FL STUDIO", url: "https://youtu.be/zUg5QchOBvM" }, { titulo: "AULA 12 - COMO GRAVAR UMA VOZ NO FL STUDIO", url: "https://youtu.be/T1-6w7Ok25o" }, { titulo: "AULA 13 - COMO REMOVER RUIDO DE UMA VOZ NO FL STUDIO", url: "https://youtu.be/pqYrZIS24Do" }, { titulo: "AULA 14 - ATALHOS NO FL STUDIO", url: "https://youtu.be/hE3CsImmPrU" }, { titulo: "AULA 15 - GRID E COMPASSOS", url: "https://youtu.be/f3yMkzRfYGA" }, { titulo: "AULA 16 - COMO ACHAR O BPM DE UMA MÚSICA", url: "https://youtu.be/QfJU7BCYi4I" }, { titulo: "AULA 17 - COMO COLOCAR QUALQUER AUDIO DENTRO DA NOTA ( VOCAL, ONE SHOT E 808 )", url: "https://youtu.be/R3xZKrng9g4" }, { titulo: "AULA 18 - COMO SEPARAR AS PARTES DE UMA MÚSICA", url: "https://youtu.be/vJcW794o5DY" }, { titulo: "AULA 19 - CHANNEL RACK AVANÇADO", url: "https://youtu.be/MFrCKJ6MLL8" }, { titulo: "AULA 20 - COMO LIGAR O CONTROLADOR MIDI", url: "https://youtu.be/4DIH2kTgP9Q" }] },
                { nome: "03. CRIAÇÃO DE RITMOS DE INSTRUMENTOS DE PERCUSSÃO", aulas: [{ titulo: "AULA 01 – OS TIMBRES USADO PARA CRIAR BEAT DE KUDURO ADOÇO", url: "LINK_AQUI" }, { titulo: "AULA 02 – COMO CRIAR A BATERIA BASE", url: "LINK_AQUI" }, { titulo: "AULA 03 – CRIAÇÃO DE PERCUSSÃO", url: "LINK_AQUI" }, { titulo: "AULA 04 – CRIAÇÃO DE BREAKS OU TRANSIÇÕES", url: "LINK_AQUI" }, { titulo: "AULA 05 – COMO USAR BREAKS JÁ PRONTOS EM AUDIO", url: "LINK_AQUI" }] },
                { nome: "04. PRODUÇÃO DE BEATS & ESTRUTURAÇÃO (PRÁTICA)", aulas: [{ titulo: "AULA 01 – CRIANDO O BEAT 01", url: "LINK_AQUI" }, { titulo: "AULA 02 - ESTRUTURAR O BEAT 01", url: "LINK_AQUI" }, { titulo: "AULA 03 – CRIANDO O BEAT 02", url: "LINK_AQUI" }, { titulo: "AULA 04 - ESTRUTURAR O BEAT 02", url: "LINK_AQUI" }, { titulo: "AULA 05 – CRIANDO O BEAT 03", url: "LINK_AQUI" }, { titulo: "AULA 06 - ESTRUTURAR O BEAT 03", url: "LINK_AQUI" }] },
                { nome: "05. A BASE DA MIX E MASTER", aulas: [{ titulo: "AULA 01 - O QUE É MIX E MASTER", url: "LINK_AQUI" }, { titulo: "AULA 02 - BALANÇO TONAL E ANALISADOR DE ESPECTRO", url: "LINK_AQUI" }, { titulo: "AULA 03 - CRIAÇÃO DE GRUPOS", url: "LINK_AQUI" }, { titulo: "AULA 04 - EQUALIZAÇÃO (O QUE É, OS TIPOS DE EQUALIZAÇÃO, OS TIPOS DE FILTROS, OS TIPOS DE EQUALIZADORES)", url: "LINK_AQUI" }, { titulo: "AULA 05 - AS FREQUENCIAS E O PAPEL DE CADA REGIÃO", url: "LINK_AQUI" }, { titulo: "AULA 06 - COMPRESSOR (O QUE É, OS TIPOS DE COMPRESSOR, OS PARAMETROS)", url: "LINK_AQUI" }, { titulo: "AULA 07 - PRE AMPLIFICADORES", url: "LINK_AQUI" }, { titulo: "AULA 08 - SATURADORES", url: "LINK_AQUI" }, { titulo: "AULA 09 - EFEITOS (DELAY E REVERB)", url: "LINK_AQUI" }, { titulo: "AULA 10 - AUTO TUNE (CORRETOR DE NOTAS)", url: "LINK_AQUI" }, { titulo: "AULA 12 - AUTOMAÇÃO", url: "LINK_AQUI" }, { titulo: "AULA 12 - LIMITER E CLIPPER", url: "LINK_AQUI" }, { titulo: "AULA 13 - SIDE CHAN", url: "LINK_AQUI" }, { titulo: "AULA 14 - IMAGEM STEREO", url: "LINK_AQUI" }] },
                { nome: "06. MIX E MASTER", aulas: [] }
            ]
        },
        {
            id: 9,
            titulo: "CURSO COMPLETO DE PRODUÇÃO DE KUDURO MELODICO + MIX E MASTER NO FL STUDIO",
            imagem: "../img/prontos/",
            desbloqueado: false,
            linkMaterial: "https://mediafire.com/exemplo",
            modulos: [
                { nome: "01. COMECE AQUI", aulas: [{ titulo: "Aula 1.1", url: "LINK_AQUI" }, { titulo: "Aula 1.2", url: "LINK_AQUI" }, { titulo: "Aula 1.3", url: "LINK_AQUI" }, { titulo: "Aula 1.4", url: "LINK_AQUI" }, { titulo: "Aula 1.5", url: "LINK_AQUI" }] },
                { nome: "02. A BASE DA PRODUÇÃO MUSICAL (FL STUDIO O BÁSICO)", aulas: [{ titulo: "AULA 01 - APRESENTAÇÃO DO AMBIENTE DO FL STUDIO", url: "https://youtu.be/tcZboMaPw5c" }, { titulo: "AULA 02 - BOTÕES DE PLAY, STOP E RECORD", url: "https://youtu.be/S9cEhJMundI" }, { titulo: "AULA 03 - CHANNEL RACK", url: "https://youtu.be/PjSxV4ol6MM" }, { titulo: "AULA 04 - PIANO ROLL", url: "https://youtu.be/O8wzgTuchL8" }, { titulo: "AULA 05 - BROWSER", url: "https://youtu.be/pmUOj8FnIJs" }, { titulo: "AULA 06 - MENU", url: "https://youtu.be/c0crY-l7lBw" }, { titulo: "AULA 07 - PLAYLIST", url: "https://youtu.be/ZtYalbddMsc" }, { titulo: "AULA 08 - MIXER", url: "https://youtu.be/LAwVXwlkSbY" }, { titulo: "AULA 09 - COMO CONFIGURAR O FL STUDIO", url: "https://youtu.be/ps9Rg_XP-wU" }, { titulo: "AULA 10 - COMO ADICIONAR OS DRUMKITS DENTRO DO FL STUDIO", url: "https://youtu.be/Qr5umV3H9qI" }, { titulo: "AULA 11 - COMO SCANNEAR PLUGINS DENTRO DO FL STUDIO", url: "https://youtu.be/zUg5QchOBvM" }, { titulo: "AULA 12 - COMO GRAVAR UMA VOZ NO FL STUDIO", url: "https://youtu.be/T1-6w7Ok25o" }, { titulo: "AULA 13 - COMO REMOVER RUIDO DE UMA VOZ NO FL STUDIO", url: "https://youtu.be/pqYrZIS24Do" }, { titulo: "AULA 14 - ATALHOS NO FL STUDIO", url: "https://youtu.be/hE3CsImmPrU" }, { titulo: "AULA 15 - GRID E COMPASSOS", url: "https://youtu.be/f3yMkzRfYGA" }, { titulo: "AULA 16 - COMO ACHAR O BPM DE UMA MÚSICA", url: "https://youtu.be/QfJU7BCYi4I" }, { titulo: "AULA 17 - COMO COLOCAR QUALQUER AUDIO DENTRO DA NOTA ( VOCAL, ONE SHOT E 808 )", url: "https://youtu.be/R3xZKrng9g4" }, { titulo: "AULA 18 - COMO SEPARAR AS PARTES DE UMA MÚSICA", url: "https://youtu.be/vJcW794o5DY" }, { titulo: "AULA 19 - CHANNEL RACK AVANÇADO", url: "https://youtu.be/MFrCKJ6MLL8" }, { titulo: "AULA 20 - COMO LIGAR O CONTROLADOR MIDI", url: "https://youtu.be/4DIH2kTgP9Q" }] },
                { nome: "03. A BASE DA TEORIA MUSICAL", aulas: [{ titulo: "AULA 01 - TEORIA MUSICAL", url: "https://youtu.be/BMV2nPGwU70" }, { titulo: "AULA 02 - NOTAS MUSICAS E NOTAS DE ACIDENTE", url: "https://youtu.be/_-XMBkyz77w" }, { titulo: "AULA 03 - CIFRAS", url: "https://youtu.be/LgDAech2LiU" }, { titulo: "AULA 04 - INTERVALOS", url: "https://youtu.be/Ok-PTt11S7g" }, { titulo: "AULA 05 - ESCALAS", url: "https://youtu.be/xApa3-95rT8" }, { titulo: "AULA 06 - FORMAÇÃO DE ESCALAS", url: "https://youtu.be/JLoNI6bFkJs" }, { titulo: "AULA 07 - ACORDES", url: "https://youtu.be/TVVHJlC-BQk" }, { titulo: "AULA 08 - CRIAÇÃO DE ACORDES", url: "https://youtu.be/QL9_zGlgyYg" }, { titulo: "AULA 09 - CAMPO HARMONICO", url: "https://youtu.be/RK7s8dSHkkU" }, { titulo: "AULA 10 - CRIANDO PROGRESSÕES DE ACORDE COM CAMPO HARMONICO", url: "https://youtu.be/MqyH_WydNfg" }, { titulo: "AULA 11 - CRIAR PROGRESSÕES DE ACORDE COM APENAS UM CLIQUE", url: "https://youtu.be/n6wvtMqNGqw" }, { titulo: "AULA 12 - COMO TIRAR AS CIFRAS DE UMA MÚSICA", url: "https://youtu.be/sLevV4Je4Gk" }, { titulo: "AULA 13 - CRIANDO PROGRESSÕES DE ACORDE COM O SCALLER", url: "https://youtu.be/OVeRVWw410E" }, { titulo: "AULA 14 - SITE PARA ENCONTRAR CIFRAS DE UMA MÚSICA", url: "https://youtu.be/37qMcwzOjyU" }, { titulo: "AULA 15 - COMO COPIAR OU ROUBAR MELODIAS DE OUTRAS MÚSICAS", url: "https://youtu.be/0f-ox5FjOdg" }, { titulo: "AULA 16 - COMO ACHAR A NOTA OU ESCALA DE UM BEAT", url: "https://youtu.be/uNxZ5FU-q-g" }] },
                { nome: "04. TIMBRES", aulas: [{ titulo: "Aula 3.1", url: "LINK_AQUI" }, { titulo: "Aula 3.2", url: "LINK_AQUI" }, { titulo: "Aula 3.3", url: "LINK_AQUI" }, { titulo: "Aula 3.4", url: "LINK_AQUI" }, { titulo: "Aula 3.5", url: "LINK_AQUI" }] },
                { nome: "05. CRIAÇÃO DE RITMOS DE INSTRUMENTOS DE PERCUSSÃO", aulas: [{ titulo: "Aula 4.1", url: "LINK_AQUI" }, { titulo: "Aula 4.2", url: "LINK_AQUI" }, { titulo: "Aula 4.3", url: "LINK_AQUI" }, { titulo: "Aula 4.4", url: "LINK_AQUI" }, { titulo: "Aula 4.5", url: "LINK_AQUI" }] },
                { nome: "06. CRIAÇÃO DE MELODIAS E HARMONIA", aulas: [{ titulo: "Aula 5.1", url: "LINK_AQUI" }, { titulo: "Aula 5.2", url: "LINK_AQUI" }, { titulo: "Aula 5.3", url: "LINK_AQUI" }, { titulo: "Aula 5.4", url: "LINK_AQUI" }, { titulo: "Aula 5.5", url: "LINK_AQUI" }] },
                { nome: "07. PRODUÇÃO DE BEATS & ESTRUTURAÇÃO (PRÁTICA)", aulas: [{ titulo: "Aula 6.1", url: "LINK_AQUI" }, { titulo: "Aula 6.2", url: "LINK_AQUI" }, { titulo: "Aula 6.3", url: "LINK_AQUI" }, { titulo: "Aula 6.4", url: "LINK_AQUI" }, { titulo: "Aula 6.5", url: "LINK_AQUI" }] },
                { nome: "08. A BASE DA MIX E MASTER", aulas: [{ titulo: "Aula 7.1", url: "LINK_AQUI" }, { titulo: "Aula 7.2", url: "LINK_AQUI" }, { titulo: "Aula 7.3", url: "LINK_AQUI" }, { titulo: "Aula 7.4", url: "LINK_AQUI" }, { titulo: "Aula 7.5", url: "LINK_AQUI" }] },
                { nome: "09. MIX E MASTER (PRATICA)", aulas: [{ titulo: "Aula 8.1", url: "LINK_AQUI" }, { titulo: "Aula 8.2", url: "LINK_AQUI" }, { titulo: "Aula 8.3", url: "LINK_AQUI" }, { titulo: "Aula 8.4", url: "LINK_AQUI" }, { titulo: "Aula 8.5", url: "LINK_AQUI" }] }
            ]
        },
        {
            id: 10,
            titulo: "CURSO COMPLETO DE PRODUÇÃO DE SEMBA + MIX E MASTER NO FL STUDIO",
            imagem: "../img/prontos/CURSO DE PRODUÇÃO DE BEATS DE SEMBA DE ANGOLA MIX E MASTER NO FL STUDIO.jpg",
            desbloqueado: false,
            linkMaterial: "https://mediafire.com/exemplo",
            modulos: [
                { nome: "01. COMECE AQUI", aulas: [{ titulo: "Aula 1.1", url: "LINK_AQUI" }, { titulo: "Aula 1.2", url: "LINK_AQUI" }, { titulo: "Aula 1.3", url: "LINK_AQUI" }, { titulo: "Aula 1.4", url: "LINK_AQUI" }, { titulo: "Aula 1.5", url: "LINK_AQUI" }] },
                { nome: "02. A BASE DA PRODUÇÃO MUSICAL (FL STUDIO O BÁSICO)", aulas: [{ titulo: "AULA 01 - APRESENTAÇÃO DO AMBIENTE DO FL STUDIO", url: "https://youtu.be/tcZboMaPw5c" }, { titulo: "AULA 02 - BOTÕES DE PLAY, STOP E RECORD", url: "https://youtu.be/S9cEhJMundI" }, { titulo: "AULA 03 - CHANNEL RACK", url: "https://youtu.be/PjSxV4ol6MM" }, { titulo: "AULA 04 - PIANO ROLL", url: "https://youtu.be/O8wzgTuchL8" }, { titulo: "AULA 05 - BROWSER", url: "https://youtu.be/pmUOj8FnIJs" }, { titulo: "AULA 06 - MENU", url: "https://youtu.be/c0crY-l7lBw" }, { titulo: "AULA 07 - PLAYLIST", url: "https://youtu.be/ZtYalbddMsc" }, { titulo: "AULA 08 - MIXER", url: "https://youtu.be/LAwVXwlkSbY" }, { titulo: "AULA 09 - COMO CONFIGURAR O FL STUDIO", url: "https://youtu.be/ps9Rg_XP-wU" }, { titulo: "AULA 10 - COMO ADICIONAR OS DRUMKITS DENTRO DO FL STUDIO", url: "https://youtu.be/Qr5umV3H9qI" }, { titulo: "AULA 11 - COMO SCANNEAR PLUGINS DENTRO DO FL STUDIO", url: "https://youtu.be/zUg5QchOBvM" }, { titulo: "AULA 12 - COMO GRAVAR UMA VOZ NO FL STUDIO", url: "https://youtu.be/T1-6w7Ok25o" }, { titulo: "AULA 13 - COMO REMOVER RUIDO DE UMA VOZ NO FL STUDIO", url: "https://youtu.be/pqYrZIS24Do" }, { titulo: "AULA 14 - ATALHOS NO FL STUDIO", url: "https://youtu.be/hE3CsImmPrU" }, { titulo: "AULA 15 - GRID E COMPASSOS", url: "https://youtu.be/f3yMkzRfYGA" }, { titulo: "AULA 16 - COMO ACHAR O BPM DE UMA MÚSICA", url: "https://youtu.be/QfJU7BCYi4I" }, { titulo: "AULA 17 - COMO COLOCAR QUALQUER AUDIO DENTRO DA NOTA ( VOCAL, ONE SHOT E 808 )", url: "https://youtu.be/R3xZKrng9g4" }, { titulo: "AULA 18 - COMO SEPARAR AS PARTES DE UMA MÚSICA", url: "https://youtu.be/vJcW794o5DY" }, { titulo: "AULA 19 - CHANNEL RACK AVANÇADO", url: "https://youtu.be/MFrCKJ6MLL8" }, { titulo: "AULA 20 - COMO LIGAR O CONTROLADOR MIDI", url: "https://youtu.be/4DIH2kTgP9Q" }] },
                { nome: "03. A BASE DA TEORIA MUSICAL", aulas: [{ titulo: "AULA 01 - TEORIA MUSICAL", url: "https://youtu.be/BMV2nPGwU70" }, { titulo: "AULA 02 - NOTAS MUSICAS E NOTAS DE ACIDENTE", url: "https://youtu.be/_-XMBkyz77w" }, { titulo: "AULA 03 - CIFRAS", url: "https://youtu.be/LgDAech2LiU" }, { titulo: "AULA 04 - INTERVALOS", url: "https://youtu.be/Ok-PTt11S7g" }, { titulo: "AULA 05 - ESCALAS", url: "https://youtu.be/xApa3-95rT8" }, { titulo: "AULA 06 - FORMAÇÃO DE ESCALAS", url: "https://youtu.be/JLoNI6bFkJs" }, { titulo: "AULA 07 - ACORDES", url: "https://youtu.be/TVVHJlC-BQk" }, { titulo: "AULA 08 - CRIAÇÃO DE ACORDES", url: "https://youtu.be/QL9_zGlgyYg" }, { titulo: "AULA 09 - CAMPO HARMONICO", url: "https://youtu.be/RK7s8dSHkkU" }, { titulo: "AULA 10 - CRIANDO PROGRESSÕES DE ACORDE COM CAMPO HARMONICO", url: "https://youtu.be/MqyH_WydNfg" }, { titulo: "AULA 11 - CRIAR PROGRESSÕES DE ACORDE COM APENAS UM CLIQUE", url: "https://youtu.be/n6wvtMqNGqw" }, { titulo: "AULA 12 - COMO TIRAR AS CIFRAS DE UMA MÚSICA", url: "https://youtu.be/sLevV4Je4Gk" }, { titulo: "AULA 13 - CRIANDO PROGRESSÕES DE ACORDE COM O SCALLER", url: "https://youtu.be/OVeRVWw410E" }, { titulo: "AULA 14 - SITE PARA ENCONTRAR CIFRAS DE UMA MÚSICA", url: "https://youtu.be/37qMcwzOjyU" }, { titulo: "AULA 15 - COMO COPIAR OU ROUBAR MELODIAS DE OUTRAS MÚSICAS", url: "https://youtu.be/0f-ox5FjOdg" }, { titulo: "AULA 16 - COMO ACHAR A NOTA OU ESCALA DE UM BEAT", url: "https://youtu.be/uNxZ5FU-q-g" }] },
                { nome: "04. TIMBRES", aulas: [{ titulo: "Aula 3.1", url: "LINK_AQUI" }, { titulo: "Aula 3.2", url: "LINK_AQUI" }, { titulo: "Aula 3.3", url: "LINK_AQUI" }, { titulo: "Aula 3.4", url: "LINK_AQUI" }, { titulo: "Aula 3.5", url: "LINK_AQUI" }] },
                { nome: "05. CRIAÇÃO DE RITMOS DE INSTRUMENTOS DE PERCUSSÃO", aulas: [{ titulo: "Aula 4.1", url: "LINK_AQUI" }, { titulo: "Aula 4.2", url: "LINK_AQUI" }, { titulo: "Aula 4.3", url: "LINK_AQUI" }, { titulo: "Aula 4.4", url: "LINK_AQUI" }, { titulo: "Aula 4.5", url: "LINK_AQUI" }] },
                { nome: "06. CRIAÇÃO DE MELODIAS E HARMONIA", aulas: [{ titulo: "Aula 5.1", url: "LINK_AQUI" }, { titulo: "Aula 5.2", url: "LINK_AQUI" }, { titulo: "Aula 5.3", url: "LINK_AQUI" }, { titulo: "Aula 5.4", url: "LINK_AQUI" }, { titulo: "Aula 5.5", url: "LINK_AQUI" }] },
                { nome: "07. PRODUÇÃO DE BEATS & ESTRUTURAÇÃO (PRÁTICA)", aulas: [{ titulo: "Aula 6.1", url: "LINK_AQUI" }, { titulo: "Aula 6.2", url: "LINK_AQUI" }, { titulo: "Aula 6.3", url: "LINK_AQUI" }, { titulo: "Aula 6.4", url: "LINK_AQUI" }, { titulo: "Aula 6.5", url: "LINK_AQUI" }] },
                { nome: "08. A BASE DA MIX E MASTER", aulas: [{ titulo: "Aula 7.1", url: "LINK_AQUI" }, { titulo: "Aula 7.2", url: "LINK_AQUI" }, { titulo: "Aula 7.3", url: "LINK_AQUI" }, { titulo: "Aula 7.4", url: "LINK_AQUI" }, { titulo: "Aula 7.5", url: "LINK_AQUI" }] },
                { nome: "09. MIX E MASTER (PRATICA)", aulas: [{ titulo: "Aula 8.1", url: "LINK_AQUI" }, { titulo: "Aula 8.2", url: "LINK_AQUI" }, { titulo: "Aula 8.3", url: "LINK_AQUI" }, { titulo: "Aula 8.4", url: "LINK_AQUI" }, { titulo: "Aula 8.5", url: "LINK_AQUI" }] }
            ]
        },
        {
            id: 11,
            titulo: "CURSO COMPLETO DE PRODUÇÃO DE TRAP + MIX E MASTER NO FL STUDIO",
            imagem: "../img/prontos/CURSO DE PRODUÇÃO DE BEATS DE TRAP MIX E MASTER NO FL STUDIO.jpg",
            desbloqueado: false,
            linkMaterial: "https://mediafire.com/exemplo",
            modulos: [
                { nome: "01. COMECE AQUI", aulas: [{ titulo: "Aula 1.1", url: "LINK_AQUI" }, { titulo: "Aula 1.2", url: "LINK_AQUI" }, { titulo: "Aula 1.3", url: "LINK_AQUI" }, { titulo: "Aula 1.4", url: "LINK_AQUI" }, { titulo: "Aula 1.5", url: "LINK_AQUI" }] },
                { nome: "02. A BASE DA PRODUÇÃO MUSICAL (FL STUDIO O BÁSICO)", aulas: [{ titulo: "AULA 01 - APRESENTAÇÃO DO AMBIENTE DO FL STUDIO", url: "https://youtu.be/tcZboMaPw5c" }, { titulo: "AULA 02 - BOTÕES DE PLAY, STOP E RECORD", url: "https://youtu.be/S9cEhJMundI" }, { titulo: "AULA 03 - CHANNEL RACK", url: "https://youtu.be/PjSxV4ol6MM" }, { titulo: "AULA 04 - PIANO ROLL", url: "https://youtu.be/O8wzgTuchL8" }, { titulo: "AULA 05 - BROWSER", url: "https://youtu.be/pmUOj8FnIJs" }, { titulo: "AULA 06 - MENU", url: "https://youtu.be/c0crY-l7lBw" }, { titulo: "AULA 07 - PLAYLIST", url: "https://youtu.be/ZtYalbddMsc" }, { titulo: "AULA 08 - MIXER", url: "https://youtu.be/LAwVXwlkSbY" }, { titulo: "AULA 09 - COMO CONFIGURAR O FL STUDIO", url: "https://youtu.be/ps9Rg_XP-wU" }, { titulo: "AULA 10 - COMO ADICIONAR OS DRUMKITS DENTRO DO FL STUDIO", url: "https://youtu.be/Qr5umV3H9qI" }, { titulo: "AULA 11 - COMO SCANNEAR PLUGINS DENTRO DO FL STUDIO", url: "https://youtu.be/zUg5QchOBvM" }, { titulo: "AULA 12 - COMO GRAVAR UMA VOZ NO FL STUDIO", url: "https://youtu.be/T1-6w7Ok25o" }, { titulo: "AULA 13 - COMO REMOVER RUIDO DE UMA VOZ NO FL STUDIO", url: "https://youtu.be/pqYrZIS24Do" }, { titulo: "AULA 14 - ATALHOS NO FL STUDIO", url: "https://youtu.be/hE3CsImmPrU" }, { titulo: "AULA 15 - GRID E COMPASSOS", url: "https://youtu.be/f3yMkzRfYGA" }, { titulo: "AULA 16 - COMO ACHAR O BPM DE UMA MÚSICA", url: "https://youtu.be/QfJU7BCYi4I" }, { titulo: "AULA 17 - COMO COLOCAR QUALQUER AUDIO DENTRO DA NOTA ( VOCAL, ONE SHOT E 808 )", url: "https://youtu.be/R3xZKrng9g4" }, { titulo: "AULA 18 - COMO SEPARAR AS PARTES DE UMA MÚSICA", url: "https://youtu.be/vJcW794o5DY" }, { titulo: "AULA 19 - CHANNEL RACK AVANÇADO", url: "https://youtu.be/MFrCKJ6MLL8" }, { titulo: "AULA 20 - COMO LIGAR O CONTROLADOR MIDI", url: "https://youtu.be/4DIH2kTgP9Q" }] },
                { nome: "03. A BASE DA TEORIA MUSICAL", aulas: [{ titulo: "AULA 01 - TEORIA MUSICAL", url: "https://youtu.be/BMV2nPGwU70" }, { titulo: "AULA 02 - NOTAS MUSICAS E NOTAS DE ACIDENTE", url: "https://youtu.be/_-XMBkyz77w" }, { titulo: "AULA 03 - CIFRAS", url: "https://youtu.be/LgDAech2LiU" }, { titulo: "AULA 04 - INTERVALOS", url: "https://youtu.be/Ok-PTt11S7g" }, { titulo: "AULA 05 - ESCALAS", url: "https://youtu.be/xApa3-95rT8" }, { titulo: "AULA 06 - FORMAÇÃO DE ESCALAS", url: "https://youtu.be/JLoNI6bFkJs" }, { titulo: "AULA 07 - ACORDES", url: "https://youtu.be/TVVHJlC-BQk" }, { titulo: "AULA 08 - CRIAÇÃO DE ACORDES", url: "https://youtu.be/QL9_zGlgyYg" }, { titulo: "AULA 09 - CAMPO HARMONICO", url: "https://youtu.be/RK7s8dSHkkU" }, { titulo: "AULA 10 - CRIANDO PROGRESSÕES DE ACORDE COM CAMPO HARMONICO", url: "https://youtu.be/MqyH_WydNfg" }, { titulo: "AULA 11 - CRIAR PROGRESSÕES DE ACORDE COM APENAS UM CLIQUE", url: "https://youtu.be/n6wvtMqNGqw" }, { titulo: "AULA 12 - COMO TIRAR AS CIFRAS DE UMA MÚSICA", url: "https://youtu.be/sLevV4Je4Gk" }, { titulo: "AULA 13 - CRIANDO PROGRESSÕES DE ACORDE COM O SCALLER", url: "https://youtu.be/OVeRVWw410E" }, { titulo: "AULA 14 - SITE PARA ENCONTRAR CIFRAS DE UMA MÚSICA", url: "https://youtu.be/37qMcwzOjyU" }, { titulo: "AULA 15 - COMO COPIAR OU ROUBAR MELODIAS DE OUTRAS MÚSICAS", url: "https://youtu.be/0f-ox5FjOdg" }, { titulo: "AULA 16 - COMO ACHAR A NOTA OU ESCALA DE UM BEAT", url: "https://youtu.be/uNxZ5FU-q-g" }] },
                { nome: "04. TIMBRES", aulas: [{ titulo: "Aula 3.1", url: "LINK_AQUI" }, { titulo: "Aula 3.2", url: "LINK_AQUI" }, { titulo: "Aula 3.3", url: "LINK_AQUI" }, { titulo: "Aula 3.4", url: "LINK_AQUI" }, { titulo: "Aula 3.5", url: "LINK_AQUI" }] },
                { nome: "05. CRIAÇÃO DE RITMOS DE INSTRUMENTOS DE PERCUSSÃO", aulas: [{ titulo: "Aula 4.1", url: "LINK_AQUI" }, { titulo: "Aula 4.2", url: "LINK_AQUI" }, { titulo: "Aula 4.3", url: "LINK_AQUI" }, { titulo: "Aula 4.4", url: "LINK_AQUI" }, { titulo: "Aula 4.5", url: "LINK_AQUI" }] },
                { nome: "06. CRIAÇÃO DE MELODIAS E HARMONIA", aulas: [{ titulo: "Aula 5.1", url: "LINK_AQUI" }, { titulo: "Aula 5.2", url: "LINK_AQUI" }, { titulo: "Aula 5.3", url: "LINK_AQUI" }, { titulo: "Aula 5.4", url: "LINK_AQUI" }, { titulo: "Aula 5.5", url: "LINK_AQUI" }] },
                { nome: "07. PRODUÇÃO DE BEATS & ESTRUTURAÇÃO (PRÁTICA)", aulas: [{ titulo: "Aula 6.1", url: "LINK_AQUI" }, { titulo: "Aula 6.2", url: "LINK_AQUI" }, { titulo: "Aula 6.3", url: "LINK_AQUI" }, { titulo: "Aula 6.4", url: "LINK_AQUI" }, { titulo: "Aula 6.5", url: "LINK_AQUI" }] },
                { nome: "08. A BASE DA MIX E MASTER", aulas: [{ titulo: "Aula 7.1", url: "LINK_AQUI" }, { titulo: "Aula 7.2", url: "LINK_AQUI" }, { titulo: "Aula 7.3", url: "LINK_AQUI" }, { titulo: "Aula 7.4", url: "LINK_AQUI" }, { titulo: "Aula 7.5", url: "LINK_AQUI" }] },
                { nome: "09. MIX E MASTER (PRATICA)", aulas: [{ titulo: "Aula 8.1", url: "LINK_AQUI" }, { titulo: "Aula 8.2", url: "LINK_AQUI" }, { titulo: "Aula 8.3", url: "LINK_AQUI" }, { titulo: "Aula 8.4", url: "LINK_AQUI" }, { titulo: "Aula 8.5", url: "LINK_AQUI" }] }
            ]
        },
        {
            id: 12,
            titulo: "CURSO COMPLETO DE COMO GANHAR NO MINIMO 50.000KZ POR SEMANA INSTALANDO PLUGINS",
            imagem: "../img/prontos/CURSO COMO BAIXAR E INSTALAR QUALQUER PLUGIN E FAZER NO MINIMO 50.000KZ POR SEMANA + TRAFEGO PAGO.jpg",
            desbloqueado: false,
            linkMaterial: "https://mediafire.com/exemplo",
            modulos: [
                { nome: "01. COMECE AQUI", aulas: [{ titulo: "OBRIGADO", url: "LINK_AQUI" }, { titulo: "COMO VAI FUNCIONAR O CURSO", url: "LINK_AQUI" }, { titulo: "INSTANDO OS PROGRAMAS PARA A FORMAÇÃO", url: "LINK_AQUI" }] },
                { nome: "02. COMO BAIXAR PLUGINS (PRÁTICA)", aulas: [{ titulo: "AULA 01 - COMO BAIXAR QUALQUER PLUGINS DE GRAÇA", url: "LINK_AQUI" }, { titulo: "AULA 02 – COMO BAIXAR QUALQUER PLUGINS DE GRAÇAS 2", url: "LINK_AQUI" }, { titulo: "AULA 03 – COMO BAIXAR QUALQUER PLUGIN DE GRAÇA SEM UTORRENT", url: "LINK_AQUI" }] },
                { nome: "03. AULAS DE INSTALAÇÃO DE PLUGINS", aulas: [{ titulo: "AULA 01 - COMO INSTALAR O OMNISPHERE", url: "LINK_AQUI" }, { titulo: "AULA 02 - T-PAIN", url: "LINK_AQUI" }, { titulo: "AULA 03 - ZENOLOGY", url: "LINK_AQUI" }, { titulo: "AULA 04 - GLADIATOR", url: "LINK_AQUI" }, { titulo: "AULA 05 - COMO INSTALAR O XPAND", url: "LINK_AQUI" }, { titulo: "AULA 06 - COMO BAIXAR E INSTALAR O WINRAR", url: "LINK_AQUI" }, { titulo: "AULA 07 - COMO INSTALAR O LOUGE LIZARD", url: "LINK_AQUI" }, { titulo: "AULA 08 - COMO INSTALAR O NEXUS 2", url: "LINK_AQUI" }, { titulo: "AULA 09 - COMO INSTALAR O HYPERSONIC", url: "LINK_AQUI" }, { titulo: "AULA 10 - COMO INSTALAR O RAVITY", url: "LINK_AQUI" }, { titulo: "AULA 11 - COMO INSTALAR O TRITON", url: "LINK_AQUI" }, { titulo: "AULA 12 - COMO INSTALAR O PURITY", url: "LINK_AQUI" }, { titulo: "AULA 13 - AUTO TUNE", url: "LINK_AQUI" }, { titulo: "AULA 14 - FABFILTER 2024", url: "LINK_AQUI" }, { titulo: "AULA 15 - DSK", url: "LINK_AQUI" }, { titulo: "AULA 16 - FRESH AIR", url: "LINK_AQUI" }, { titulo: "AULA 17 - HALF TIME", url: "LINK_AQUI" }, { titulo: "AULA 18 - NEURAL NOTES", url: "LINK_AQUI" }, { titulo: "AULA 19 - MELODYNE", url: "LINK_AQUI" }, { titulo: "AULA 20 - PLASMA", url: "LINK_AQUI" }, { titulo: "AULA 21 - T-RACK 5", url: "LINK_AQUI" }, { titulo: "AULA 22 - DUNE 3", url: "LINK_AQUI" }, { titulo: "AULA 23 - CLARIPHONIC", url: "LINK_AQUI" }, { titulo: "AULA 24 - ARCADE", url: "LINK_AQUI" }, { titulo: "AULA 25 - ADDICTIVE KEYS", url: "LINK_AQUI" }, { titulo: "AULA 26 - ADDICTIVE DRUMS", url: "LINK_AQUI" }, { titulo: "AULA 27 - TRAPSOUL", url: "LINK_AQUI" }, { titulo: "AULA 28 - AMPLE GUITAR M 3", url: "LINK_AQUI" }, { titulo: "AULA 29 - SCALLER DETECTOR", url: "LINK_AQUI" }, { titulo: "AULA 30 - SEVEN SPECTRUM ANALAYSER", url: "LINK_AQUI" }, { titulo: "AULA 31 - SKY KEYS", url: "LINK_AQUI" }, { titulo: "AULA 32 - AMPLE GUITAR TC", url: "LINK_AQUI" }] },
                { nome: "04. CRIAÇÃO E CONFIGURAÇÃO DE CONTAS", aulas: [{ titulo: "AULA 01 – CRIANDO A PAGINA DO FACEBOOK", url: "LINK_AQUI" }, { titulo: "AULA 02 - CRIANDO A CONTA NO WHATSAP BUSINESS", url: "LINK_AQUI" }, { titulo: "AULA 03 – CRIANDO O LOGOTIPO E A FOTO DE CAPA PARA SUA EMPRESA", url: "LINK_AQUI" }, { titulo: "AULA 04 – COMO CONFIGURAR A PAGINA DO FACEBOOK", url: "LINK_AQUI" }, { titulo: "AULA 05 – COMO CONFIGURAR O SEU WHATSAP BUSINESS", url: "LINK_AQUI" }] },
                { nome: "05. CRIAÇÃO DE CONTA VISA", aulas: [{ titulo: "AULA 01 – COMO CRIAR UMA CONTA VISA", url: "LINK_AQUI" }, { titulo: "AULA 02 – COMO ACTIVAR A SUA CONTA VISA", url: "LINK_AQUI" }, { titulo: "AULA 03 – COMO CARREGAR A SUA CONTA VISA", url: "LINK_AQUI" }] },
                { nome: "06. CRIAÇÃO DE ARTES", aulas: [{ titulo: "AULA 01 – COMO CRIAR O LOGOTIPO", url: "LINK_AQUI" }, { titulo: "AULA 02 – COMO CRIAR O FLYER DA PUBLICIDADE", url: "LINK_AQUI" }] },
                { nome: "07. CRIANDO A PUBLICAÇÃO E O ANUNCIO", aulas: [{ titulo: "AULA 01 – COMO CRIAR UMA OFERTA", url: "LINK_AQUI" }, { titulo: "AULA 02 – COMO CRIAR UMA PUBLICAÇÃO IRRESISTIVEL", url: "LINK_AQUI" }, { titulo: "AULA 03 – SOLTAR O ANUNCIO", url: "LINK_AQUI" }] },
                { nome: "08. ATENDIMENTO AO CLIENTE (PRÁTICA)", aulas: [{ titulo: "AULA 01 – RESPONDER MENSAGENS", url: "LINK_AQUI" }] }
            ]
        },
        {
            id: 13,
            titulo: "CURSO DE COMO GANHAR NO MINIMO 50.000KZ POR SEMANA CRIANDO E VENDENDO DRUMKITS",
            imagem: "../img/prontos/CURSO COMO CRIAR E VENDER DRUMKITS E FAZER 50.000KZ POR SEMANA + TRAFEGO PAGO.jpg",
            desbloqueado: false,
            linkMaterial: "https://mediafire.com/exemplo",
            modulos: [
                { nome: "01. COMECE AQUI", aulas: [{ titulo: "OBRIGADO", url: "LINK_AQUI" }, { titulo: "COMO VAI FUNCIONAR O CURSO", url: "LINK_AQUI" }, { titulo: "COMO BAIXAR E INSTALAR AS FERRAMENTAS USADAS NO CURSO", url: "LINK_AQUI" }] },
                { nome: "02. CRIAÇÃO DE CONTAS", aulas: [{ titulo: "AULA 01 – CRIAR CONTA NO WHATSAP", url: "LINK_AQUI" }, { titulo: "AULA 02 – CRIAR A PÁGINA NO FACEBOOK", url: "LINK_AQUI" }, { titulo: "AULA 03 – CRIAR UMA CONTA DE EMAIL", url: "LINK_AQUI" }, { titulo: "AULA 04 – INSTALAR OS PROGRAMAS DA FORMAÇÃO", url: "LINK_AQUI" }, { titulo: "AULA 05 – CRIANDO CONTA NO CHATGPT", url: "LINK_AQUI" }] },
                { nome: "03. TUDO SOBRE OS DRUMKITS", aulas: [{ titulo: "AULA 01 - COMO BAIXAR DRUMKITS DE GRAÇA PELO SITE", url: "LINK_AQUI" }, { titulo: "AULA 02 - COMO BAIXAR DRUMKITS DE GRAÇA PELO YOUTUBE", url: "LINK_AQUI" }, { titulo: "AULA 03 - COMO BAIXAR MUSICAS ANGOLANAS EM SITES", url: "LINK_AQUI" }, { titulo: "AULA 04 - COMO BAIXAR MUSICAS E BEATS", url: "LINK_AQUI" }, { titulo: "AULA 05 - COMO ORGANIZAR AS MUSICAS E BEATS", url: "LINK_AQUI" }, { titulo: "AULA 06 - COMO EXTRAIR AS PEÇAS DE UMA MUSICA PART 1", url: "LINK_AQUI" }, { titulo: "AULA 07 - COMO EXTRAIR AS PEÇAS DE UMA MUSICA PART 2", url: "LINK_AQUI" }, { titulo: "AULA 08 - COMO MELHORAR AS PEÇAS DOS DRUMKITS", url: "LINK_AQUI" }, { titulo: "AULA 09 - COMO CRIAR OS MIDIS", url: "LINK_AQUI" }, { titulo: "AULA 10 - COMO CRIAR UM ONE SHOT", url: "LINK_AQUI" }, { titulo: "AULA 11 - COMO EXPORTAR UM INSTRUMENTO OU UM PRESET", url: "LINK_AQUI" }, { titulo: "AULA 12 - COMO RENOMEAR OS ARQUIVOS", url: "LINK_AQUI" }, { titulo: "AULA 13 - COMO DETECTAR OS ACORDES TOCADO NUMA MUSICA", url: "LINK_AQUI" }, { titulo: "AULA 14 - COMO SABER A ESCALA DE UMA MUSICA", url: "LINK_AQUI" }, { titulo: "AULA 15 - COMO CRIAR A CAPA PARA O SEU PACOTE DE DRUMKIT", url: "LINK_AQUI" }, { titulo: "AULA 16 - COMO FINALIZAR  O PACOTE DE DRUMKIT", url: "LINK_AQUI" }] },
                { nome: "04. CRIAÇÃO E CONFIGURAÇÃO DE CONTAS", aulas: [{ titulo: "AULA 01 – CRIANDO A PAGINA DO FACEBOOK", url: "LINK_AQUI" }, { titulo: "AULA 02 - CRIANDO A CONTA NO WHATSAP BUSINESS", url: "LINK_AQUI" }, { titulo: "AULA 03 – CRIANDO O LOGOTIPO E A FOTO DE CAPA PARA SUA EMPRESA", url: "LINK_AQUI" }, { titulo: "AULA 04 – COMO CONFIGURAR A PAGINA DO FACEBOOK", url: "LINK_AQUI" }, { titulo: "AULA 05 – COMO CONFIGURAR O SEU WHATSAP BUSINESS", url: "LINK_AQUI" }] },
                { nome: "05. CRIAÇÃO DE CONTA VISA", aulas: [{ titulo: "AULA 01 – COMO CRIAR UMA CONTA VISA", url: "LINK_AQUI" }, { titulo: "AULA 02 – COMO ACTIVAR A SUA CONTA VISA", url: "LINK_AQUI" }, { titulo: "AULA 03 – COMO CARREGAR A SUA CONTA VISA", url: "LINK_AQUI" }] },
                { nome: "06. CRIANDO A PUBLICAÇÃO E O ANUNCIO", aulas: [{ titulo: "AULA 01 – COMO CRIAR UMA OFERTA", url: "LINK_AQUI" }, { titulo: "AULA 02 – COMO GRAVAR O VIDEO DA PUBLICIDADE", url: "LINK_AQUI" }, { titulo: "AULA 03 – COMO CRIAR UMA PUBLICAÇÃO IRRESISTIVEL", url: "LINK_AQUI" }, { titulo: "AULA 04 – SOLTAR O ANUNCIO", url: "LINK_AQUI" }] },
                { nome: "07. ATENDIMENTO AO CLIENTE (PRÁTICA)", aulas: [{ titulo: "AULA 01 – RESPONDER MENSAGEM", url: "LINK_AQUI" }] }
            ]
        }
    ],
    drumkits: [
        // --- NOVOS ITENS ADICIONADOS DA SUA LISTA DE IMAGENS ---
        { id: 158, titulo: "DRUMKIT CU DOCE DE AFRO BEAT", imagem: "../img/prontos/DRUMKIT CU DOCE DE AFRO BEAT.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 159, titulo: "DRUMKIT CU DOCE DE AFRO HOUSE", imagem: "../img/prontos/DRUMKIT CU DOCE DE AFRO HOUSE.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 160, titulo: "DRUMKIT GUETHO ZOUK PEDRA 2025", imagem: "../img/prontos/DRUMKIT GUETHO ZOUK PEDRA 2025.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 161, titulo: "DRUMKIT KUDURO ADOÇO", imagem: "../img/prontos/DRUMKIT KUDURO ADOÇO.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 162, titulo: "DRUMKIT NOVA GERAÇÃO DE AFRO HOUSE", imagem: "../img/prontos/DRUMKIT NOVA GERAÇÃO DE AFRO HOUSE.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 163, titulo: "DRUMKIT NOVA GERAÇÃO DE GUETHO ZOUK", imagem: "../img/prontos/DRUMKIT NOVA GERAÇÃO DE GUETHO ZOUK.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 164, titulo: "DRUMKIT PEDRA DE AFRO HOUSE 2026", imagem: "../img/prontos/DRUMKIT PEDRA DE AFRO HOUSE 2026.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 165, titulo: "DRUMKIT PESCONCINHO DE AFRO HOUSE", imagem: "../img/prontos/DRUMKIT PESCONCINHO DE AFRO HOUSE.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 166, titulo: "DRUMKIT PESCONCINHO DE AFROBEAT", imagem: "../img/prontos/DRUMKIT PESCONCINHO DE AFROBEAT.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 167, titulo: "DRUMKIT PESCONCINHO DE GUETHO ZOUK", imagem: "../img/prontos/DRUMKIT PESCONCINHO DE GUETHO ZOUK.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 168, titulo: "DRUMKIT TABUA MISTA KUDURO MELODICO", imagem: "../img/prontos/DRUMKIT TABUA MISTA KUDURO MELODICO.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 169, titulo: "DRUMKIT TABUA MISTA TRAP", imagem: "../img/prontos/DRUMKIT TABUA MISTA TRAP.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" }
    ],
   flps: [
        { id: 201, titulo: "FLP AFRO HOUSE - PRA MATAR - ME PROD.LONEKE NO BEAT", imagem: "../img/prontos/FLP AFRO HOUSE - PRA MATAR - ME PROD.LONEKE NO BEAT.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 202, titulo: "FLP APANHOU TEC TEC", imagem: "../img/prontos/FLP APANHOU TEC TEC.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 203, titulo: "FLP BANANA", imagem: "../img/prontos/FLP BANANA.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 204, titulo: "FLP BAZA SÓ", imagem: "../img/prontos/FLP BAZA SÓ.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 205, titulo: "FLP DRENA NA UK", imagem: "../img/prontos/FLP DRENA NA UK.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 206, titulo: "FLP GUETHO ZOUK PIANO", imagem: "../img/prontos/FLP GUETHO ZOUK PIANO.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 207, titulo: "FLP GUETHO ZOUK RIJO", imagem: "../img/prontos/FLP GUETHO ZOUK RIJO.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 208, titulo: "FLP I NEED YOU", imagem: "../img/prontos/FLP I NEED YOU.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 209, titulo: "FLP MINHA EX", imagem: "../img/prontos/FLP MINHA EX.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 210, titulo: "FLP MONEY FOLLOW", imagem: "../img/prontos/FLP MONEY FOLLOW.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 211, titulo: "FLP NÃO FICA TEIMOSO VAIS SOFRER", imagem: "../img/prontos/FLP NÃO FICA TEIMOSO VAIS SOFRER.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 212, titulo: "FLP NÃO TOMARAM BANHO", imagem: "../img/prontos/FLP NÃO TOMARAM BANHO.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 213, titulo: "FLP NOSSO AMOR ESTA CUIAR", imagem: "../img/prontos/FLP NOSSO AMOR ESTA CUIAR.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 214, titulo: "FLP PEDRA", imagem: "../img/prontos/FLP PEDRA.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 215, titulo: "FLP PERIGOSA", imagem: "../img/prontos/FLP PERIGOSA.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 216, titulo: "FLP PESO PESADO", imagem: "../img/prontos/FLP PESO PESADO.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 217, titulo: "FLP PROLONGADO", imagem: "../img/prontos/FLP PROLONGADO.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 218, titulo: "FLP SEMBA MORENA", imagem: "../img/prontos/FLP SEMBA MORENA.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 219, titulo: "FLP SÓ TENHO DOIS MIL SERÁ QUE POSSO TE MANDAR", imagem: "../img/prontos/FLP SÓ TENHO DOIS MIL SERÁ QUE POSSO TE MANDAR.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 220, titulo: "FLP TENHO SIDA", imagem: "../img/prontos/FLP TENHO SIDA.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 221, titulo: "FLP TODO MAL QUE EU TE FIZ", imagem: "../img/prontos/FLP TODO MAL QUE EU TE FIZ.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 222, titulo: "FLP TYPE BEAT C4 PEDRO", imagem: "../img/prontos/FLP TYPE BEAT C4 PEDRO.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" }
    ],
    loops: [
        { id: 301, titulo: "LOOP KIT TABUA MISTA DE KIZOMBA VOLUME 2", imagem: "../img/prontos/LOOP KIT TABUA MISTA DE KIZOMBA VOLUME 2.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 302, titulo: "LOOP KIT TABUA MISTA DE KIZOMBA", imagem: "../img/prontos/LOOP KIT TABUA MISTA DE KIZOMBA.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 303, titulo: "LOOP KIT TABUA MISTA DE REGGAE", imagem: "../img/prontos/LOOP KIT TABUA MISTA DE REGGAE.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 304, titulo: "LOOP KIT TABUA MISTA DE SEBENE", imagem: "../img/prontos/LOOP KIT TABUA MISTA DE SEBENE.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 305, titulo: "LOOP KIT TABUA MISTA DE SEMBA VOLUME 2", imagem: "../img/prontos/LOOP KIT TABUA MISTA DE SEMBA VOLUME 2.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 306, titulo: "LOOP KIT TABUA MISTA DE SEMBA", imagem: "../img/prontos/LOOP KIT TABUA MISTA DE SEMBA.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" }
    ],
    plugins: [
        { id: 401, titulo: "PACKS DE PLUGINS DE INSTRUMENTOS VIRTUAIS DE AFROBEAT", imagem: "../img/prontos/PACKS DE PLUGINS DE INSTRUMENTOS VIRTUAIS DE AFROBEAT.jpg", desbloqueado: false, linkDownload: "https://mediafire.com", preview: "https://www.youtube.com/watch?v=SEU_LINK_AQUI" },
        { id: 402, titulo: "PACKS DE PLUGINS DE INSTRUMENTOS VIRTUAIS DE GUETHO ZOUK", imagem: "../img/prontos/PACKS DE PLUGINS DE INSTRUMENTOS VIRTUAIS DE GUETHO ZOUK.jpg", desbloqueado: false, linkDownload: "https://mediafire.com", preview: "https://www.youtube.com/watch?v=SEU_LINK_AQUI" },
        { id: 403, titulo: "PACKS DE PLUGINS DE INSTRUMENTOS VIRTUAIS DE SEMBA", imagem: "../img/prontos/PACKS DE PLUGINS DE INSTRUMENTOS VIRTUAIS DE SEMBA.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 404, titulo: "PACKS DE PLUGINS DE INSTRUMENTOS VIRTUAIS DE TRAP", imagem: "../img/prontos/PACKS DE PLUGINS DE INSTRUMENTOS VIRTUAIS DE TRAP.jpg", desbloqueado: false, linkDownload: "https://mediafire.com" },
        { id: 405, titulo: "PACKS DE PLUGINS DE MIX E MASTER", imagem: "../img/prontos/PACKS DE PLUGINS DE MIX E MASTER.jpg", desbloqueado: false, linkDownload: "https://mediafire.com", preview: "https://www.youtube.com/watch?v=SEU_LINK_AQUI" }
    ],
    ebooks: []
};
