// produtos.js
const produtos = [
    // ================= ROUND 1 =================
    // Drumkits
    {
        id: 56,
        uuid: null,
        slug: "drumkit-tabua-mista-de-afro-house",
        titulo: "DRUMKIT TABUA MISTA DE AFRO HOUSE",
        categoria: "drumkits",
        descricao: "O verdadeiro arsenal para produtores de Afro House, contendo timbres pesados e grooves limpos.",
        imagem: "img/prontos/DRUMKIT TABUA MISTA DE AFRO HOUSE.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 189,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-tabua-mista-de-afro-house",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 18,
        uuid: null,
        slug: "drumkit-chelsea-dinorath",
        titulo: "DRUMKIT CHELSEA DINORATH",
        categoria: "drumkits",
        descricao: "Texturas acústicas e percussões suaves no estilo intimista da Chelsea Dinorath.",
        imagem: "img/prontos/DRUMKIT CHELSEA DINORATH.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 143,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-chelsea-dinorath",
        videoLink: "https://youtu.be/2G9oYB8f9Ys",
        destaque: true
    },
    // Cursos (Começando por Distribuição e Afro House)
    {
        id: 3,
        uuid: null,
        slug: "curso-completo-como-distribuir-musicas-nas-plataformas-de-stream",
        titulo: "CURSO COMPLETO COMO DISTRIBUIR MÚSICAS NAS PLATAFORMAS DE STREAM",
        categoria: "cursos",
        descricao: "Aprenda a colocar as suas músicas no Spotify, Apple Music e Deezer de forma profissional.",
        imagem: "img/prontos/CURSO COMPLETO COMO DISTRIBUIR MÚSICAS NAS PLATAFORMAS DE STREAM.jpg",
        precoAntigo: 20000,
        precoAtual: 10000,
        vendas: 54,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/curso-completo-como-distribuir-musicas-nas-plataformas-de-stream",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 6,
        uuid: null,
        slug: "curso-completo-de-producao-de-beats-de-afro-house-kuduro-mix-e-master-no-fl-studio",
        titulo: "CURSO COMPLETO DE PRODUÇÃO DE BEATS DE AFRO HOUSE KUDURO + MIX E MASTER NO FL STUDIO",
        categoria: "cursos",
        descricao: "Aprenda a fazer batidas profissionais de Afro House e Kuduro que dominam as pistas nacionais.",
        imagem: "img/prontos/CURSO COMPLETO DE PRODUÇÃO DE BEATS DE AFRO HOUSE KUDURO + MIX E MASTER NO FL STUDIO.jpg",
        precoAntigo: 20000,
        precoAtual: 10000,
        vendas: 110,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/curso-completo-de-producao-de-beats-de-afro-house-kuduro-mix-e-master-no-fl-studio",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    // FLPs
    {
        id: 72,
        uuid: null,
        slug: "flp-nao-fica-teimoso-vais-sofrer",
        titulo: "FLP NÃO FICA TEIMOSO VAIS SOFRER",
        categoria: "flp",
        descricao: "Estude o balanço exato dos claps e a timbragem das percussões contidas neste super hit.",
        imagem: "img/prontos/FLP NÃO FICA TEIMOSO VAIS SOFRER.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 125,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-nao-fica-teimoso-vais-sofrer",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 63,
        uuid: null,
        slug: "flp-afro-house-pra-matar-me-prod-loneke-no-beat",
        titulo: "FLP AFRO HOUSE - PRA MATAR - ME PROD.LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Projeto aberto completo no FL Studio para você estudar arranjo, mixagem e estrutura.",
        imagem: "img/prontos/FLP AFRO HOUSE - PRA MATAR - ME PROD.LONEKE NO BEAT.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 154,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-afro-house-pra-matar-me-prod-loneke-no-beat",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 80,
        uuid: null,
        slug: "flp-todo-mal-que-eu-te-fiz",
        titulo: "FLP TODO MAL QUE EU TE FIZ",
        categoria: "flp",
        descricao: "Analise a estrutura de mixagem vocal e progressões melódicas contidas neste projeto aberto.",
        imagem: "img/prontos/FLP TODO MAL QUE EU TE FIZ.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 143,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-todo-mal-que-eu-te-fiz",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 64,
        uuid: null,
        slug: "flp-apanhou-tec-tec",
        titulo: "FLP APANHOU TEC TEC",
        categoria: "flp",
        descricao: "Estude o projeto de um dos maiores hits de Kuduro e domine o ritmo das pistas.",
        imagem: "img/prontos/FLP APANHOU TEC TEC.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 98,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-apanhou-tec-tec",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },

    // ================= ROUND 2 =================
    // Drumkits
    {
        id: 45,
        uuid: null,
        slug: "drumkit-meyson",
        titulo: "DRUMKIT MEYSON",
        categoria: "drumkits",
        descricao: "Seleção exclusiva de timbres, kicks e efeitos inovadores para enriquecer suas produções.",
        imagem: "img/prontos/DRUMKIT MEYSON.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 59,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-meyson",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 12,
        uuid: null,
        slug: "drumkit-3finer",
        titulo: "DRUMKIT 3FINER",
        categoria: "drumkits",
        descricao: "Sons de bateria premium totalmente processados e prontos para uso profissional.",
        imagem: "img/prontos/DRUMKIT 3FINER.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 45,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-3finer",
        videoLink: "https://youtu.be/Hh3eN2q1dJY",
        destaque: true
    },
    // Cursos (Guetho Zouk e Semba)
    {
        id: 7,
        uuid: null,
        slug: "curso-completo-de-producao-de-beats-de-guetho-zouk-mix-e-master-no-fl-studio",
        titulo: "CURSO COMPLETO DE PRODUÇÃO DE BEATS DE GUETHO ZOUK + MIX E MASTER NO FL STUDIO",
        categoria: "cursos",
        descricao: "Passo a passo completo focado nas melodias e batidas envolventes do Guetho Zouk.",
        imagem: "img/prontos/CURSO COMPLETO DE PRODUÇÃO DE BEATS DE GUETHO ZOUK + MIX E MASTER NO FL STUDIO.jpg",
        precoAntigo: 20000,
        precoAtual: 10000,
        vendas: 78,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/curso-completo-de-producao-de-beats-de-guetho-zouk-mix-e-master-no-fl-studio",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 8,
        uuid: null,
        slug: "curso-completo-de-producao-de-beats-de-semba-mix-e-master-no-fl-studio",
        titulo: "CURSO COMPLETO DE PRODUÇÃO DE BEATS DE SEMBA + MIX E MASTER NO FL STUDIO",
        categoria: "cursos",
        descricao: "Traga a nossa essência tradicional para o digital de forma autêntica e altamente profissional.",
        imagem: "img/prontos/CURSO COMPLETO DE PRODUÇÃO DE BEATS DE SEMBA + MIX E MASTER NO FL STUDIO.jpg",
        precoAntigo: 20000,
        precoAtual: 10000,
        vendas: 92,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/curso-completo-de-producao-de-beats-de-semba-mix-e-master-no-fl-studio",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    // FLPs
    {
        id: 76,
        uuid: null,
        slug: "flp-peso-pesado",
        titulo: "FLP PESO PESADO",
        categoria: "flp",
        descricao: "Mixagem avançada de sub-graves aplicada a um instrumental focado em Rap de impacto.",
        imagem: "img/prontos/FLP PESO PESADO.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 95,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-peso-pesado",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 68,
        uuid: null,
        slug: "flp-guetho-zouk-rijo",
        titulo: "FLP GUETHO ZOUK RIJO",
        categoria: "flp",
        descricao: "Projeto com groove pesado e focado no balanço rítmico do Zouk comercial moderno.",
        imagem: "img/prontos/FLP GUETHO ZOUK RIJO.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 89,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-guetho-zouk-rijo",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 78,
        uuid: null,
        slug: "flp-so-tenho-dois-mil-sera-que-posso-te-mandar",
        titulo: "FLP SÓ TENHO DOIS MIL SERÁ QUE POSSO TE MANDAR",
        categoria: "flp",
        descricao: "Veja como foi construído o arranjo satírico e rítmico deste projeto de enorme engajamento de rua.",
        imagem: "img/prontos/FLP SÓ TENHO DOIS MIL SERÁ QUE POSSO TE MANDAR.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 178,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-so-tenho-dois-mil-sera-que-posso-te-mandar",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 69,
        uuid: null,
        slug: "flp-i-need-you",
        titulo: "FLP I NEED YOU",
        categoria: "flp",
        descricao: "Estude as cadeias de efeitos e automações melódicas contidas neste projeto aberto profissional.",
        imagem: "img/prontos/FLP I NEED YOU.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 56,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-i-need-you",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },

    // ================= ROUND 3 =================
    // Drumkits
    {
        id: 49,
        uuid: null,
        slug: "drumkit-pedra-de-afro-house-2026",
        titulo: "DRUMKIT PEDRA DE AFRO HOUSE 2026",
        categoria: "drumkits",
        descricao: "O verdadeiro arsenal de loops pesados e pedras para quebrar as pistas em 2026.",
        imagem: "img/prontos/DRUMKIT PEDRA DE AFRO HOUSE 2026.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 140,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-pedra-de-afro-house-2026",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 13,
        uuid: null,
        slug: "drumkit-anderson-mario",
        titulo: "DRUMKIT ANDERSON MÁRIO",
        categoria: "drumkits",
        descricao: "Kit exclusivo inspirado na sonoridade e grooves do artista Anderson Mário.",
        imagem: "img/prontos/DRUMKIT ANDERSON MÁRIO.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 32,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-anderson-mario",
        videoLink: "https://WFi5Zxn3gN4",
        destaque: false
    },
    {
        id: 31,
        uuid: null,
        slug: "drumkit-fariento-de-semba",
        titulo: "DRUMKIT FARIENTO DE SEMBA",
        categoria: "drumkits",
        descricao: "Percussões acústicas e ritmos tradicionais de Semba gravados com máxima fidelidade sonora.",
        imagem: "img/prontos/DRUMKIT FARIENTO DE SEMBA.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 73,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-fariento-de-semba",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    // Cursos
    {
        id: 4,
        uuid: null,
        slug: "curso-completo-de-como-baixar-e-instalar-qualquer-plugin-e-fazer-no-minimo-50000kz-por-semana",
        titulo: "CURSO COMPLETO DE COMO BAIXAR E  INSTALAR QUALQUER PLUGIN E FAZER NO MINIMO 50.000KZ POR SEMANA",
        categoria: "cursos",
        descricao: "Um guia prático com estratégias secretas de monetização técnica em estúdios de gravação.",
        imagem: "img/prontos/CURSO COMPLETO DE COMO BAIXAR E  INSTALAR QUALQUER PLUGIN E FAZER NO MINIMO 50.000KZ POR SEMANA.jpg",
        precoAntigo: 20000,
        precoAtual: 15000,
        vendas: 120,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/curso-completo-de-como-baixar-e-instalar-qualquer-plugin-e-fazer-no-minimo-50000kz-por-semana",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 11,
        uuid: null,
        slug: "curso-de-como-ganhar-no-minimo-50000kz-por-mes-criando-artes-com-inteligencia-artificial",
        titulo: "CURSO DE COMO GANHAR NO MINIMO 50.000KZ POR MES CRIANDO ARTES COM INTELIGENCIA ARTIFICIAL",
        categoria: "cursos",
        descricao: "Aprenda a dominar as ferramentas de I.A. para criar capas de beats, flyers e faturar no mercado digital.",
        imagem: "img/prontos/CURSO DE COMO GANHAR NO MINIMO 50.000KZ POR MES CRIANDO ARTES COM INTELIGENCIA ARTIFICIAL.jpg",
        precoAntigo: 20000,
        precoAtual: 10000,
        vendas: 215,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/curso-de-como-ganhar-no-minimo-50000kz-por-mes-criando-artes-com-inteligencia-artificial",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    // FLPs
    {
        id: 70,
        uuid: null,
        slug: "flp-minha-ex",
        titulo: "FLP MINHA EX",
        categoria: "flp",
        descricao: "Estrutura comercial aberta para entender o arranjo perfeito de uma track de sucesso.",
        imagem: "img/prontos/FLP MINHA EX.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 112,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-minha-ex",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 65,
        uuid: null,
        slug: "flp-banana",
        titulo: "FLP BANANA",
        categoria: "flp",
        descricao: "Projeto com timbragem agressiva e arranjo totalmente detalhado para produtores.",
        imagem: "img/prontos/FLP BANANA.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 47,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-banana",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 71,
        uuid: null,
        slug: "flp-money-follow",
        titulo: "FLP MONEY FOLLOW",
        categoria: "flp",
        descricao: "Linhas de baixo pesadas e timbragem agressiva para produções no estilo Hip-Hop/Trap.",
        imagem: "img/prontos/FLP MONEY FOLLOW.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 78,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-money-follow",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 66,
        uuid: null,
        slug: "flp-drena-na-uk",
        titulo: "FLP DRENA NA UK",
        categoria: "flp",
        descricao: "Projeto aberto focado em sonoridades de Drill e texturas agressivas no padrão britânico.",
        imagem: "img/prontos/FLP DRENA NA UK.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 65,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-drena-na-uk",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },

    // ================= ROUND 4 =================
    // Drumkits
    {
        id: 52,
        uuid: null,
        slug: "drumkit-rui-orlando",
        titulo: "DRUMKIT RUI ORLANDO",
        categoria: "drumkits",
        descricao: "Texturas românticas e percussões harmônicas suaves inspiradas nas faixas de Rui Orlando.",
        imagem: "img/prontos/DRUMKIT RUI ORLANDO.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 165,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-rui-orlando",
        videoLink: "https://youtu.be/Yt0FRt4DqT4",
        destaque: true
    },
    // Cursos
    {
        id: 2,
        uuid: null,
        slug: "curso-completo-como-criar-e-vender-drumkits-e-fazer-50000kz-por-semana",
        titulo: "CURSO COMPLETO COMO CRIAR E VENDER DRUMKITS E FAZER 50.000KZ POR SEMANA",
        categoria: "cursos",
        descricao: "O método definitivo para monetizar o seu conhecimento musical e faturar semanalmente.",
        imagem: "img/prontos/CURSO COMPLETO COMO CRIAR E VENDER DRUMKITS E FAZER 50.000KZ POR SEMANA.jpg",
        precoAntigo: 50000,
        precoAtual: 30000,
        vendas: 85,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/curso-completo-como-criar-e-vender-drumkits-e-fazer-50000kz-por-semana",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 5,
        uuid: null,
        slug: "curso-completo-de-como-baixar-e-instalar-qualquer-plugin",
        titulo: "CURSO COMPLETO DE COMO BAIXAR E  INSTALAR QUALQUER PLUGIN",
        categoria: "cursos",
        descricao: "Esqueça os erros de instalação. Passo a passo para ter qualquer ferramenta rodando liso no seu DAW.",
        imagem: "img/prontos/CURSO COMPLETO DE COMO BAIXAR E  INSTALAR QUALQUER PLUGIN.jpg",
        precoAntigo: 70000,
        precoAtual: 3000,
        vendas: 95,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/curso-completo-de-como-baixar-e-instalar-qualquer-plugin",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    // FLPs
    {
        id: 73,
        uuid: null,
        slug: "flp-nao-tomaram-banho",
        titulo: "FLP NÃO TOMARAM BANHO",
        categoria: "flp",
        descricao: "Projeto aberto icônico com estruturas de automação agressivas prontas para estudar no FL Studio.",
        imagem: "img/prontos/FLP NÃO TOMARAM BANHO.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 143,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-nao-tomaram-banho",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 75,
        uuid: null,
        slug: "flp-perigosa",
        titulo: "FLP PERIGOSA",
        categoria: "flp",
        descricao: "Estude as progressões de acordes sensuais e transições profissionais em formato aberto.",
        imagem: "img/prontos/FLP PERIGOSA.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 134,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-perigosa",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 67,
        uuid: null,
        slug: "flp-guetho-zouk-piano",
        titulo: "FLP GUETHO ZOUK PIANO",
        categoria: "flp",
        descricao: "Harmonias sofisticadas e linhas de piano prontas para serem dissecadas e aplicadas.",
        imagem: "img/prontos/FLP GUETHO ZOUK PIANO.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 72,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-guetho-zouk-piano",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 74,
        uuid: null,
        slug: "flp-pedra",
        titulo: "FLP PEDRA",
        categoria: "flp",
        descricao: "Estrutura crua e rítmica de alta energia focada no estilo de Kuduro pesado das ruas.",
        imagem: "img/prontos/FLP PEDRA.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 89,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-pedra",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },

    // ================= ROUND 5 =================
    // Drumkits
    {
        id: 42,
        uuid: null,
        slug: "drumkit-landrick",
        titulo: "DRUMKIT LANDRICK",
        categoria: "drumkits",
        descricao: "Sons envolventes, kicks macios e percussões sob medida para Kizomba com a vibe de Landrick.",
        imagem: "img/prontos/DRUMKIT LANDRICK.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 195,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-landrick",
        videoLink: "https://youtu.be/cYH3UzmG25A",
        destaque: true
    },
    {
        id: 14,
        uuid: null,
        slug: "drumkit-anna-joyce",
        titulo: "DRUMKIT ANNA JOYCE",
        categoria: "drumkits",
        descricao: "Elementos percussivos marcantes e melódicos baseados nos maiores sucessos de Anna Joyce.",
        imagem: "img/prontos/DRUMKIT ANNA JOYCE.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 89,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-anna-joyce",
        videoLink: "https://youtu.be/2CsU5AO5_XM",
        destaque: true
    },
    {
        id: 35,
        uuid: null,
        slug: "drumkit-gerilson-insrael",
        titulo: "DRUMKIT GERILSON INSRAEL",
        categoria: "drumkits",
        descricao: "Elementos percussivos de elite inspirados na identidade sonora e sucessos de Gerilson Insrael.",
        imagem: "img/prontos/DRUMKIT GERILSON INSRAEL.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 320,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-gerilson-insrael",
        videoLink: "https://youtu.be/TfS_ano9rNw",
        destaque: true
    },
    // Cursos (Últimos Cursos Disponíveis)
    {
        id: 10,
        uuid: null,
        slug: "curso-de-como-criar-uma-conta-na-redotpay",
        titulo: "CURSO DE COMO CRIAR UMA CONTA NA REDOTPAY",
        categoria: "cursos",
        descricao: "Aprenda a configurar e validar a sua conta para receber pagamentos internacionais sem complicações.",
        imagem: "img/prontos/CURSO DE COMO CRIAR UMA CONTA NA REDOTPAY.jpg",
        precoAntigo: 20000,
        precoAtual: 10000,
        vendas: 143,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/curso-de-como-criar-uma-conta-na-redotpay",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 9,
        uuid: null,
        slug: "curso-de-como-baixar-e-instalar-qualquer-programa-de-producao-musical",
        titulo: "CURSO DE COMO BAIXAR E INSTALAR QUALQUER PROGRAMA DE PRODUÇÃO MUSICAL",
        categoria: "cursos",
        descricao: "Monte o seu estúdio digital sem dores de cabeça com este tutorial completo passo a passo.",
        imagem: "img/prontos/CURSO DE COMO BAIXAR E INSTALAR QUALQUER PROGRAMA DE PRODUÇÃO MUSICAL.jpg",
        precoAntigo: 20000,
        precoAtual: 10000,
        vendas: 165,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/curso-de-como-baixar-e-instalar-qualquer-programa-de-producao-musical",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    // FLPs
    {
        id: 77,
        uuid: null,
        slug: "flp-prolongado",
        titulo: "FLP PROLONGADO",
        categoria: "flp",
        descricao: "Estude automações estruturais complexas ideais para estender a energia das suas tracks.",
        imagem: "img/prontos/FLP PROLONGADO.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 61,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-prolongado",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 79,
        uuid: null,
        slug: "flp-tenho-sida",
        titulo: "FLP TENHO SIDA",
        categoria: "flp",
        descricao: "Projeto com foco em arranjos de conscientização urbana e ritmos tradicionais de impacto.",
        imagem: "img/prontos/FLP TENHO SIDA.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 104,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-tenho-sida",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },

    // ================= ITENS EXTRAS & PRODUTOS RESTANTES =================
    // Plugins & Loops
    {
        id: 1,
        uuid: null,
        slug: "packs-de-plugins-de-mix-e-master",
        titulo: "PACKS DE PLUGINS DE MIX E MASTER",
        categoria: "plugins",
        descricao: "A seleção de ferramentas essenciais para dar clareza, peso e volume comercial às suas tracks.",
        imagem: "img/prontos/PACKS DE PLUGINS DE MIX E MASTER.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 40,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/packs-de-plugins-de-mix-e-master",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 81,
        uuid: null,
        slug: "loop-kit-tabua-mista-de-semba",
        titulo: "LOOP KIT TABUA MISTA DE SEMBA",
        categoria: "loops",
        descricao: "Grooves autênticos de Semba gravados por percussionistas profissionais da nossa praça.",
        imagem: "img/prontos/LOOP KIT TABUA MISTA DE SEMBA.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 210,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/loop-kit-tabua-mista-de-semba",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },

    // Outros Drumkits restantes
    {
        id: 29,
        uuid: null,
        slug: "drumkit-fariento-de-guetho-zouk",
        titulo: "DRUMKIT FARIENTO DE GUETHO ZOUK",
        categoria: "drumkits",
        descricao: "Timbragem comercial limpa e suave feita especialmente para hits românticos e envolventes.",
        imagem: "img/prontos/DRUMKIT FARIENTO DE GUETHO ZOUK.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 87,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-fariento-de-guetho-zouk",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 58,
        uuid: null,
        slug: "drumkit-tabua-mista-de-guetho-zouk",
        titulo: "DRUMKIT TABUA MISTA DE GUETHO ZOUK",
        categoria: "drumkits",
        descricao: "A união dos melhores kicks, claps e percussões cadenciadas voltadas ao Guetho Zouk.",
        imagem: "img/prontos/DRUMKIT TABUA MISTA DE GUETHO ZOUK.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 104,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-tabua-mista-de-guetho-zouk",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 22,
        uuid: null,
        slug: "drumkit-dream-boyz",
        titulo: "DRUMKIT DREAM BOYZ",
        categoria: "drumkits",
        descricao: "Os timbres clássicos e futuristas que marcaram o estilo inconfundível dos Dream Boyz.",
        imagem: "img/prontos/DRUMKIT DREAM BOYZ.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 42,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-dream-boyz",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 46,
        uuid: null,
        slug: "drumkit-nelasta",
        titulo: "DRUMKIT NELASTA",
        categoria: "drumkits",
        descricao: "Sons pesados de Afro House com a assinatura e o balanço inconfundível do icônico DJ Nelasta.",
        imagem: "img/prontos/DRUMKIT NELASTA.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 280,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-nelasta",
        videoLink: "https://youtu.be/mDyYc-Axkc8",
        destaque: true
    },
    {
        id: 15,
        uuid: null,
        slug: "drumkit-arieth-feijo",
        titulo: "DRUMKIT ARIETH FEIJÓ",
        categoria: "drumkits",
        descricao: "Elementos focados em Kizomba e Zouk com a assinatura rítmica de Arieth Feijó.",
        imagem: "img/prontos/DRUMKIT ARIETH FEIJÓ.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 27,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-arieth-feijo",
        videoLink: "https://youtu.be/UJ_oFALJEbE",
        destaque: false
    },
    {
        id: 55,
        uuid: null,
        slug: "drumkit-tabanka-djaz",
        titulo: "DRUMKIT TABANKA DJAZ",
        categoria: "drumkits",
        descricao: "Elementos percussivos lendários inspirados na sonoridade clássica e histórica dos Tabanka Djaz.",
        imagem: "img/prontos/DRUMKIT TABANKA DJAZ.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 79,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-tabanka-djaz",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 30,
        uuid: null,
        slug: "drumkit-fariento-de-kuduro-melodico",
        titulo: "DRUMKIT FARIENTO DE KUDURO MELODICO",
        categoria: "drumkits",
        descricao: "Batidas limpas e claps estalados otimizados para destacar seu Kuduro Melódico nas pistas.",
        imagem: "img/prontos/DRUMKIT FARIENTO DE KUDURO MELODICO.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 115,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-fariento-de-kuduro-melodico",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 17,
        uuid: null,
        slug: "drumkit-cef",
        titulo: "DRUMKIT CEF",
        categoria: "drumkits",
        descricao: "Kicks profundos e percussões rítmicas com a vibe inconfundível do CEF.",
        imagem: "img/prontos/DRUMKIT CEF.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 112,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-cef",
        videoLink: "https://youtu.be/a1Tn1FVXqaA",
        destaque: true
    },
    {
        id: 59,
        uuid: null,
        slug: "drumkit-tabua-mista-de-semba",
        titulo: "DRUMKIT TABUA MISTA DE SEMBA",
        categoria: "drumkits",
        descricao: "Kit de ferramentas obrigatório para quem quer programar Semba profissional no computador.",
        imagem: "img/prontos/DRUMKIT TABUA MISTA DE SEMBA.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 165,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-tabua-mista-de-semba",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 21,
        uuid: null,
        slug: "drumkit-doddy",
        titulo: "DRUMKIT DODDY",
        categoria: "drumkits",
        descricao: "Kits de percussão modernos ideais para flows urbanos e beats comerciais.",
        imagem: "img/prontos/DRUMKIT DODDY.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 51,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-doddy",
        videoLink: "https://youtu.be/NUXfQqL_XWI",
        destaque: false
    },
    {
        id: 16,
        uuid: null,
        slug: "drumkit-button-rose",
        titulo: "DRUMKIT BUTTON ROSE",
        categoria: "drumkits",
        descricao: "Sons versáteis ideais para produções modernas baseadas no estilo de Button Rose.",
        imagem: "img/prontos/DRUMKIT BUTTON ROSE.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 34,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-button-rose",
        videoLink: "https://youtu.be/HN0v0do36YM",
        destaque: false
    },
    {
        id: 47,
        uuid: null,
        slug: "drumkit-nova-geracao-de-afro-house",
        titulo: "DRUMKIT NOVA GERAÇÃO DE AFRO HOUSE",
        categoria: "drumkits",
        descricao: "Loops frescos, congas processadas e timbres pesados para a nova geração do Afro House.",
        imagem: "img/prontos/DRUMKIT NOVA GERAÇÃO DE AFRO HOUSE.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 112,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-nova-geracao-de-afro-house",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 51,
        uuid: null,
        slug: "drumkit-puto-portugues",
        titulo: "DRUMKIT PUTO PORTUGUES",
        categoria: "drumkits",
        descricao: "Sons clássicos e batidas orgânicas com o tempero e balanço fiel de Puto Português.",
        imagem: "img/prontos/DRUMKIT PUTO PORTUGUES.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 120,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-puto-portugues",
        videoLink: "https://youtu.be/uIzVyBNOFvQ",
        destaque: false
    },
    {
        id: 39,
        uuid: null,
        slug: "drumkit-j-levy",
        titulo: "DRUMKIT J LEVY",
        categoria: "drumkits",
        descricao: "Timbres refinados e grooves de altíssima qualidade inspirados nas produções de J Levy.",
        imagem: "img/prontos/DRUMKIT J LEVY.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 64,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-j-levy",
        videoLink: "https://youtu.be/ecgMBGxY1lE",
        destaque: false
    },
    {
        id: 44,
        uuid: null,
        slug: "drumkit-mano-chaba",
        titulo: "DRUMKIT MANO CHABA",
        categoria: "drumkits",
        descricao: "Kits percussivos ideais para criar balanços e grooves nativos de enorme impacto.",
        imagem: "img/prontos/DRUMKIT MANO CHABA.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 41,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-mano-chaba",
        videoLink: "https://youtu.be/wQu6HMjXaR0",
        destaque: false
    },
    {
        id: 50,
        uuid: null,
        slug: "drumkit-pesconcinho-de-guetho-zouk",
        titulo: "DRUMKIT PESCONCINHO DE GUETHO ZOUK",
        categoria: "drumkits",
        descricao: "Groove cadenciado, lento e sensual para hits inesquecíveis de Guetho Zouk.",
        imagem: "img/prontos/DRUMKIT PESCONCINHO DE GUETHO ZOUK.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 93,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-pesconcinho-de-guetho-zouk",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 24,
        uuid: null,
        slug: "drumkit-fabio-hustle",
        titulo: "DRUMKIT FABIO HUSTLE",
        categoria: "drumkits",
        descricao: "A pegada certeira e os timbres dinâmicos baseados nas produções de Fabio Hustle.",
        imagem: "img/prontos/DRUMKIT FABIO HUSTLE.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 55,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-fabio-hustle",
        videoLink: "https://youtu.be/BkrafWZfhUU",
        destaque: false
    },
    {
        id: 43,
        uuid: null,
        slug: "drumkit-lil-magro",
        titulo: "DRUMKIT LIL MAGRO",
        categoria: "drumkits",
        descricao: "A pegada rítmica moderna e urbana perfeita para hits de rua e produções rápidas.",
        imagem: "img/prontos/DRUMKIT LIL MAGRO.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 83,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-lil-magro",
        videoLink: "https://youtu.be/5x-W6xma8_0",
        destaque: false
    },
    {
        id: 34,
        uuid: null,
        slug: "drumkit-ganah-boyz",
        titulo: "DRUMKIT GANAH BOYZ",
        categoria: "drumkits",
        descricao: "Sons pesados e agressivos inspirados no estilo de produção dos Ganah Boyz.",
        imagem: "img/prontos/DRUMKIT GANAH BOYZ.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 49,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-ganah-boyz",
        videoLink: "https://youtu.be/qrbmVDGMBBE",
        destaque: false
    },
    {
        id: 54,
        uuid: null,
        slug: "drumkit-soarito",
        titulo: "DRUMKIT SOARITO",
        categoria: "drumkits",
        descricao: "Grooves aconchegantes e percussões rítmicas suaves ideais para R&B / Kizomba modernos.",
        imagem: "img/prontos/DRUMKIT SOARITO.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 140,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-soarito",
        videoLink: "https://youtu.be/jbCC5rfdM5U",
        destaque: false
    },
    {
        id: 48,
        uuid: null,
        slug: "drumkit-paulelson",
        titulo: "DRUMKIT PAULELSON",
        categoria: "drumkits",
        descricao: "808s agressivos e caixas cortantes inspiradas diretamente na sonoridade de Paulelson.",
        imagem: "img/prontos/DRUMKIT PAULELSON.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 175,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-paulelson",
        videoLink: "https://youtu.be/2TRILY5s-7I",
        destaque: true
    },
    {
        id: 60,
        uuid: null,
        slug: "drumkit-thamires-moiane",
        titulo: "DRUMKIT THAMIRES MOIANE",
        categoria: "drumkits",
        descricao: "Sonoridade limpa e rítmica baseada na linha musical e groove de Thamires Moiane.",
        imagem: "img/prontos/DRUMKIT THAMIRES MOIANE.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 74,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-thamires-moiane",
        videoLink: "https://youtu.be/Ool9-REMGdg",
        destaque: false
    },
    {
        id: 61,
        uuid: null,
        slug: "drumkit-tsunami",
        titulo: "DRUMKIT TSUNAMI",
        categoria: "drumkits",
        descricao: "Uma verdadeira onda de claps pesados e kicks avassaladores para produções de rua.",
        imagem: "img/prontos/DRUMKIT TSUNAMI.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 96,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-tsunami",
        videoLink: "https://youtu.be/cwimXoz3qe4",
        destaque: false
    },
    {
        id: 53,
        uuid: null,
        slug: "drumkit-sini",
        titulo: "DRUMKIT SINI",
        categoria: "drumkits",
        descricao: "Sons de bateria versáteis com engenharia limpa e moderna, prontos para qualquer DAW.",
        imagem: "img/prontos/DRUMKIT SINI.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 38,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-sini",
        videoLink: "https://youtu.be/3KTrzDLxkrY",
        destaque: false
    },
    {
        id: 57,
        uuid: null,
        slug: "drumkit-tabua-mista-de-afrobeat",
        titulo: "DRUMKIT TABUA MISTA DE AFROBEAT",
        categoria: "drumkits",
        descricao: "Seleção completa e mista com timbragens perfeitas para estourar no mercado de Afrobeat.",
        imagem: "img/prontos/DRUMKIT TABUA MISTA DE AFROBEAT.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 132,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-tabua-mista-de-afrobeat",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 37,
        uuid: null,
        slug: "drumkit-hit-de-guetho-zouk",
        titulo: "DRUMKIT HIT DE GUETHO ZOUK",
        categoria: "drumkits",
        descricao: "A seleção ideal de kicks, shakers e claps para colocar seus beats de Guetho Zouk no topo.",
        imagem: "img/prontos/DRUMKIT HIT DE GUETHO ZOUK.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 105,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-hit-de-guetho-zouk",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 20,
        uuid: null,
        slug: "drumkit-cu-doce-de-guetho-zouk",
        titulo: "DRUMKIT CÚ DOCE DE GUETHO ZOUK",
        categoria: "drumkits",
        descricao: "Sons doces e cadenciados perfeitamente lapidados para produções de Guetho Zouk.",
        imagem: "img/prontos/DRUMKIT CÚ DOCE DE GUETHO ZOUK.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 98,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-cu-doce-de-guetho-zouk",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 19,
        uuid: null,
        slug: "drumkit-cleyton-m",
        titulo: "DRUMKIT CLEYTON M",
        categoria: "drumkits",
        descricao: "Bateria explosiva e percussões ideais para Afro House e Kuduro moderno.",
        imagem: "img/prontos/DRUMKIT CLEYTON M.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 67,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/drumkit-cleyton-m",
        videoLink: "https://youtu.be/pucY3zXY7Xc",
        destaque: false
    },

    // ================= NOVOS FLPs ADICIONADOS =================
    {
        id: 82,
        uuid: null,
        slug: "flp-baza-so",
        titulo: "FLP BAZA SÓ",
        categoria: "flp",
        descricao: "Estude a estrutura, arranjo e a batida contagiante contida neste projeto aberto no FL Studio.",
        imagem: "img/prontos/FLP BAZA SÓ.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 85,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-baza-so",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 83,
        uuid: null,
        slug: "flp-nosso-amor-esta-cuiar",
        titulo: "FLP NOSSO AMOR ESTA CUIAR",
        categoria: "flp",
        descricao: "Projeto de Kizomba/Zouk romântico completo para estudar mixagem de vozes e estrutura.",
        imagem: "img/prontos/FLP NOSSO AMOR ESTA CUIAR.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 120,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-nosso-amor-esta-cuiar",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 84,
        uuid: null,
        slug: "flp-semba-morena",
        titulo: "FLP SEMBA MORENA",
        categoria: "flp",
        descricao: "Descubra os segredos de programação e groove de um Semba tradicional de alta qualidade.",
        imagem: "img/prontos/FLP SEMBA MORENA.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 95,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-semba-morena",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 85,
        uuid: null,
        slug: "flp-type-beat-c4-pedro",
        titulo: "FLP TYPE BEAT C4 PEDRO",
        categoria: "flp",
        descricao: "Estude as harmonias e a levada de Kizomba romântica inspirada no C4 Pedro.",
        imagem: "img/prontos/FLP TYPE BEAT C4 PEDRO.jpg",
        precoAntigo: 3000,
        precoAtual: 1000,
        vendas: 110,
        linkCheckout: "https://checkout.lonekenobeat.com/pay/flp-type-beat-c4-pedro",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    }
];
