// produtos.js
const produtos = [
    {
        id: 44,
        uuid: null,
        slug: "flp-pedra",
        titulo: "FLP PEDRA PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Estrutura crua e rítmica de alta energia focada no estilo de Kuduro pesado das ruas.",
        imagem: "img/prontos/FLP PEDRA.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 89,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/61ab5c2a-47fc-43a9-82da-ed654c808286",
        videoLink: "https://youtu.be/u1-_DwlJALg",
        destaque: false
    },
    {
        id: 12,
        uuid: null,
        slug: "drumkit-cu-doce-de-afro-house",
        titulo: "DRUMKIT CÚ DOCE DE AFRO HOUSE",
        categoria: "drumkits",
        descricao: "Linhas de percussão e timbres quentes focados no melhor do Afro House atual.",
        imagem: "img/prontos/DRUMKIT CU DOCE DE AFRO HOUSE.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 144,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/e3075be8-e8ee-4f3a-b997-5bae4d7a3443",
        videoLink: "https://youtu.be/u1-_DwlJALg",
        destaque: false
    },
    {
        id: 1,
        uuid: null,
        slug: "curso-como-baixar-e-instalar-qualquer-plugin-e-fazer-no-minimo-50000kz-por-semana-trafego-pago",
        titulo: "CURSO COMPLETO DE COMO GANHAR NO MINIMO 50.000KZ POR SEMANA INSTALANDO PLUGINS",
        categoria: "cursos",
        descricao: "Um guia prático com estratégias de monetização e tráfego pago para faturar alto com plugins.",
        imagem: "img/prontos/CURSO COMO BAIXAR E INSTALAR QUALQUER PLUGIN E FAZER NO MINIMO 50.000KZ POR SEMANA + TRAFEGO PAGO.jpg",
        precoAntigo: 20000,
        precoAtual: 10000,
        vendas: 164,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/7ab6b227-65e0-4d68-bf44-73ce78aa22a3",
        videoLink: "https://youtu.be/u1-_DwlJALg",
        destaque: true
    },
    {
        id: 38,
        uuid: null,
        slug: "flp-i-need-you",
        titulo: "FLP I NEED YOU - PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Estude as cadeias de efeitos e automações melódicas contidas neste projeto aberto profissional.",
        imagem: "img/prontos/FLP I NEED YOU.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 56,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/01634129-ff36-46f2-b72d-a1ae385606a5",
        videoLink: "https://youtu.be/u1-_DwlJALg",
        destaque: false
    },
    {
        id: 28,
        uuid: null,
        slug: "drumkit-tabua-mista-de-semba",
        titulo: "DRUMKIT TABUA MISTA DE SEMBA @LONEKENOBEAT",
        categoria: "drumkits",
        descricao: "Kit de ferramentas obrigatório para quem quer programar Semba profissional no computador.",
        imagem: "img/prontos/DRUMKIT TABUA MISTA DE SEMBA.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 165,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/039f55f0-c609-4881-b46a-28a64d6c4715",
        videoLink: "https://youtu.be/u1-_DwlJALg",
        destaque: true
    },
    {
        id: 9,
        uuid: null,
        slug: "curso-de-produção-de-beats-de-semba-de-angola-mix-e-master-no-fl-studio",
        titulo: "CURSO COMPLETO DE PRODUÇÃO DE SEMBA + MIX E MASTER NO FL STUDIO",
        categoria: "cursos",
        descricao: "Traga a nossa essência tradicional do Semba para o digital com autenticidade e alta qualidade técnica.",
        imagem: "img/prontos/CURSO DE PRODUÇÃO DE BEATS DE SEMBA DE ANGOLA MIX E MASTER NO FL STUDIO.jpg",
        precoAntigo: 20000,
        precoAtual: 10000,
        vendas: 112,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/711b546e-d077-4600-8bd8-85a91b8a801c",
        videoLink: "https://youtu.be/u1-_DwlJALg",
        destaque: true
    },
    {
        id: 36,
        uuid: null,
        slug: "flp-guetho-zouk-piano",
        titulo: "FLP GUETHO ZOUK PIANO PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Harmonias sofisticadas e linhas de piano prontas para serem dissecadas e aplicadas.",
        imagem: "img/prontos/FLP GUETHO ZOUK PIANO.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 82,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/c0bc98fd-23ac-4144-8d96-1f18a54c2f1f",
        videoLink: "https://youtu.be/u1-_DwlJALg",
        destaque: true
    },
    {
        id: 15,
        uuid: null,
        slug: "drumkit-fariento-de-afro-house",
        titulo: "DRUMKIT DE AFRO HOUSE O FARIENTO",
        categoria: "drumkits",
        descricao: "Kicks pesados e elements percussivos de elite para incendiar as pistas.",
        imagem: "img/prontos/DRUMKIT FARIENTO DE AFRO HOUSE.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 156,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/d1ea3265-19aa-44cd-8e47-5afaa47053bd",
        videoLink: "https://youtu.be/u1-_DwlJALg",
        destaque: false
    },
    {
        id: 41,
        uuid: null,
        slug: "flp-nao-fica-teimoso-vais-sofrer",
        titulo: "FLP NÃO FICA TEIMOSO VAIS SOFRER PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Estude o balanço exato dos claps e a timbragem das percussões contidas neste super hit.",
        imagem: "img/prontos/FLP NÃO FICA TEIMOSO VAIS SOFRER.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 125,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/87b96538-3065-4252-8689-c31a0b2cf082",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 2,
        uuid: null,
        slug: "curso-como-criar-e-vender-drumkits-e-fazer-50000kz-por-semana-trafego-pago",
        titulo: "CURSO DE COMO GANHAR NO MINIMO 50.000KZ POR SEMANA CRIANDO E VENDENDO DRUMKITS",
        categoria: "cursos",
        descricao: "O método definitivo para empacotar o seu conhecimento musical, vender drumkits e lucrar semanalmente.",
        imagem: "img/prontos/CURSO COMO CRIAR E VENDER DRUMKITS E FAZER 50.000KZ POR SEMANA + TRAFEGO PAGO.jpg",
        precoAntigo: 20000,
        precoAtual: 10000,
        vendas: 178,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/46d9c31a-f4e1-4494-9b66-8e16d051cf1b",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 48,
        uuid: null,
        slug: "flp-semba-morena",
        titulo: "FLP MORENA - PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Descubra os segredos de programação e groove de um Semba tradicional de alta qualidade.",
        imagem: "img/prontos/FLP SEMBA MORENA.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 95,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/6bfe4434-4f79-48ea-9d21-d842fab8da64",
        videoLink: "https://youtu.be/u1-_DwlJALg",
        destaque: false
    },
    {
        id: 18,
        uuid: null,
        slug: "drumkit-kuduro-adoco",
        titulo: "DRUMKIT DE KUDURO ADOÇO @LONEKENOBEAT",
        categoria: "drumkits",
        descricao: "Elementos percussivos agressivos e rápidos para adoçar e quebrar no Kuduro.",
        imagem: "img/prontos/DRUMKIT KUDURO ADOÇO.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 91,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/58d5f291-0490-4e78-a9a4-72a116113124",
        videoLink: "https://youtu.be/u1-_DwlJALg",
        destaque: false
    },
    {
        id: 27,
        uuid: null,
        slug: "drumkit-tabua-mista-de-guetho-zouk",
        titulo: "DRUMKIT TABUA MISTA DE GUETHO ZOUK",
        categoria: "drumkits",
        descricao: "A união dos melhores kicks, claps e percussões cadenciadas voltadas ao Guetho Zouk.",
        imagem: "img/prontos/DRUMKIT TABUA MISTA DE GUETHO ZOUK.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 104,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/4a3dabfa-f3b1-49ba-b0a3-dade1e73e37e",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 43,
        uuid: null,
        slug: "flp-nosso-amor-esta-cuiar",
        titulo: "FLP NOSSO AMOR ESTA CUIAR PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Projeto de Kizomba/Zouk romântico completo para estudar mixagem de vozes e estrutura.",
        imagem: "img/prontos/FLP NOSSO AMOR ESTA CUIAR.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 118,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/9d4a8232-b2bd-4d85-8e29-38ff5d090312",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 6,
        uuid: null,
        slug: "curso-de-produção-de-beats-de-afro-house-kuduro-de-angola-mix-e-master-no-fl-studio",
        titulo: "CURSO COMPLETO DE PRODUÇÃO DE AFRO HOUSE + MIX E MASTER NO FL STUDIO",
        categoria: "cursos",
        descricao: "Aprenda a fazer batidas profissionais de Afro House e Kuduro que dominam as pistas nacionais.",
        imagem: "img/prontos/CURSO DE PRODUÇÃO DE BEATS DE AFRO HOUSE KUDURO DE ANGOLA MIX E MASTER NO FL STUDIO.jpg",
        precoAntigo: 20000,
        precoAtual: 10000,
        vendas: 156,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/617bd593-ef1b-463c-bdb1-57cf12ae7708",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 11,
        uuid: null,
        slug: "drumkit-cu-doce-de-afro-beat",
        titulo: "DRUMKIT CÚ DOCE DE AFRO BEAT",
        categoria: "drumkits",
        descricao: "Grooves autênticos e texturas envolventes para produções profissionais de Afro Beat.",
        imagem: "img/prontos/DRUMKIT CU DOCE DE AFRO BEAT.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 189,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/447444ef-9c4c-4522-840f-bd31e484a226",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 31,
        uuid: null,
        slug: "flp-afro-house-pra-matar-me-prod-loneke-no-beat",
        titulo: "FLP PRA MATAR-ME PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Projeto aberto completo no FL Studio para você estudar arranjo, mixagem e estrutura.",
        imagem: "img/prontos/FLP AFRO HOUSE - PRA MATAR - ME PROD.LONEKE NO BEAT.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 154,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/74065855-e6b2-4b94-82e2-4a4ead40f8b3",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 25,
        uuid: null,
        slug: "drumkit-tabua-mista-de-afro-house",
        titulo: "DRUMKIT TABUA MISTA DE AFRO HOUSE",
        categoria: "drumkits",
        descricao: "O verdadeiro arsenal para produtores de Afro House, contendo timbres pesados e grooves limpos.",
        imagem: "img/prontos/DRUMKIT TABUA MISTA DE AFRO HOUSE.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 189,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/bc8c9596-0f88-4714-a395-3187655c144f",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 4,
        uuid: null,
        slug: "curso-de-como-baixar-distribuir-musicas-nas-plataformas-de-stream",
        titulo: "CURSO COMPLETO DE COMO GANHAR NO MINIMO 50.000KZ POR SEMANA DISTRIBUINDO MUSICAS NAS PLATAFORMAS DIGITAIS",
        categoria: "cursos",
        descricao: "Aprenda a colocar as suas faixas no Spotify, Apple Music e Deezer de forma profissional.",
        imagem: "img/prontos/CURSO DE COMO BAIXAR DISTRIBUIR MUSICAS NAS PLATAFORMAS DE STREAM.jpg",
        precoAntigo: 20000,
        precoAtual: 10000,
        vendas: 87,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/6d483db2-e118-4cc0-bd80-8380e3b9ffea",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 46,
        uuid: null,
        slug: "flp-peso-pesado",
        titulo: "FLP PESO PESADO - PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Mixagem avançada de sub-graves aplicada a um instrumental focado em Rap de impacto.",
        imagem: "img/prontos/FLP PESO PESADO.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 95,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/15922098-0441-4f2b-860c-54816bf5f3fc",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 32,
        uuid: null,
        slug: "flp-apanhou-tec-tec",
        titulo: "FLP APANHOU TEC TEC PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Estude o projeto de um dos maiores hits de Kuduro e domine o ritmo das pistas.",
        imagem: "img/prontos/FLP APANHOU TEC TEC.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 98,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/31e08a8d-de48-4109-838e-43a5bcafdf59",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 19,
        uuid: null,
        slug: "drumkit-nova-geracao-de-afro-house",
        titulo: "DRUMKIT NOVA GERAÇÃO DE AFRO HOUSE",
        categoria: "drumkits",
        descricao: "Timbres modernos e inovadores para a nova vaga de produtores de Afro House.",
        imagem: "img/prontos/DRUMKIT NOVA GERAÇÃO DE AFRO HOUSE.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 119,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/e84f4eb3-dd1d-439a-bb4b-f86295022135",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 37,
        uuid: null,
        slug: "flp-guetho-zouk-rijo",
        titulo: "FLP GUETHO ZOUK RIJO - PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Projeto com groove pesado e focado no balanço rítmico do Zouk comercial moderno.",
        imagem: "img/prontos/FLP GUETHO ZOUK RIJO.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 89,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/fdf600fa-3f7b-4463-a8a0-59513c74e1a5",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 42,
        uuid: null,
        slug: "flp-nao-tomaram-banho",
        titulo: "FLP NÃO TOMARAM BANHO PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Projeto aberto icônico com estruturas de automação agressivas prontas para estudar no FL Studio.",
        imagem: "img/prontos/FLP NÃO TOMARAM BANHO.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 143,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/5bca4630-760c-41e5-ab30-e19acd287d90",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 13,
        uuid: null,
        slug: "drumkit-cu-doce-de-guetho-zouk",
        titulo: "DRUMKIT CÚ DOCE DE GUETHO ZOUK",
        categoria: "drumkits",
        descricao: "O balanço ideal e cadenciado para batidas sensuais de Guetho Zouk.",
        imagem: "img/prontos/DRUMKIT CÚ DOCE DE GUETHO ZOUK.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 95,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/aaa23235-6e4b-4b04-9830-d19e4c5c4764",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 3,
        uuid: null,
        slug: "curso-como-ganhar-no-minimo-50000kz-por-mes-criando-artes-grafica-trafego-pago",
        titulo: "CURSO COMPLETO DE COMO GANHAR NO MINIMO 50.000KZ POR SEMANA CRIANDO ARTES COM INTELIGENCIA ARTIFICIAL",
        categoria: "cursos",
        descricao: "Domine o design de capas de beats e flyers e use tráfego pago para atrair clientes recorrentes.",
        imagem: "img/prontos/CURSO COMO GANHAR NO MINIMO 50.000KZ POR MÊS CRIANDO ARTES GRAFICA + TRAFEGO PAGO.jpg",
        precoAntigo: 20000,
        precoAtual: 10000,
        vendas: 132,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/513dd20d-335e-4980-8cb9-c578123fc0eb",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 50,
        uuid: null,
        slug: "flp-tenho-sida",
        titulo: "FLP TENHO SIDA PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Projeto com foco em arranjos de conscientização urbana e ritmos tradicionais de impacto.",
        imagem: "img/prontos/FLP TENHO SIDA.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 104,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/c44fdca7-f2b1-4146-8fdf-26c5e1a013f8",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 45,
        uuid: null,
        slug: "flp-perigosa",
        titulo: "FLP PERIGOSA - PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Estude as progressões de acordes sensuais e transições profissionais em formato aberto.",
        imagem: "img/prontos/FLP PERIGOSA.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 134,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/06166c98-9975-4ba2-851c-8812c4924330",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 29,
        uuid: null,
        slug: "drumkit-tabua-mista-kuduro-melodico",
        titulo: "DRUMKIT TABUA MISTA KUDURO MELODICO",
        categoria: "drumkits",
        descricao: "Batidas limpas e claps estalados otimizados para destacar seu Kuduro Melódico nas pistas.",
        imagem: "img/prontos/DRUMKIT TABUA MISTA KUDURO MELODICO.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 215,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/e7e2540e-58c0-4482-8293-1b20adfa2db4",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 40,
        uuid: null,
        slug: "flp-money-follow",
        titulo: "FLP MONEY FOLLOW PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Linhas de baixo pesadas e timbragem agressiva para produções no estilo Hip-Hop/Trap.",
        imagem: "img/prontos/FLP MONEY FOLLOW.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 78,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/a6f3f4de-bfba-468f-9288-2568e595997d",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 8,
        uuid: null,
        slug: "curso-de-produção-de-beats-de-guetho-zouk-de-angola-mix-e-master-no-fl-studio",
        titulo: "CURSO COMPLETO DE PRODUÇÃO DE GUETHO ZOUK + MIX E MASTER NO FL STUDIO",
        categoria: "cursos",
        descricao: "Passo a passo completo focado nas melodias envolventes e mixagem perfeita de Guetho Zouk.",
        imagem: "img/prontos/CURSO DE PRODUÇÃO DE BEATS DE GUETHO ZOUK DE ANGOLA MIX E MASTER NO FL STUDIO.jpg",
        precoAntigo: 20000,
        precoAtual: 10000,
        vendas: 142,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/bf3d79dc-35a0-4f6e-a653-5f32d9b31b4d",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 34,
        uuid: null,
        slug: "flp-baza-so",
        titulo: "FLP BAZA SÓ - PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Estude a estrutura, arranjo e a batida contagiante contida neste projeto aberto no FL Studio.",
        imagem: "img/prontos/FLP BAZA SÓ.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 142,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/8c71f68b-1707-440c-9f8f-5e1f5a269fbf",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 51,
        uuid: null,
        slug: "flp-todo-mal-que-eu-te-fiz",
        titulo: "FLP TODO MAL QUE EU TE FIZ PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Analise a estrutura de mixagem vocal e progressões melódicas contidas neste projeto aberto.",
        imagem: "img/prontos/FLP TODO MAL QUE EU TE FIZ.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 143,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/00f7931d-e6d3-42f9-a185-dc9cfc510aea",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: true
    },
    {
        id: 35,
        uuid: null,
        slug: "flp-drena-na-uk",
        titulo: "FLP DRENA NA UK PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Projeto aberto focado em sonoridades de Drill e texturas agressivas no padrão britânico.",
        imagem: "img/prontos/FLP DRENA NA UK.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 65,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/6bf29ea0-a2e2-423b-bf73-cc6b3c6a1295",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    },
    {
        id: 47,
        uuid: null,
        slug: "flp-prolongado",
        titulo: "FLP PROLONGADO PROD. LONEKE NO BEAT",
        categoria: "flp",
        descricao: "Estude automações estruturais complexas ideais para estender a energia das suas tracks.",
        imagem: "img/prontos/FLP PROLONGADO.jpg",
        precoAntigo: 3000,
        precoAtual: 500,
        vendas: 61,
        linkCheckout: "https://paygooo.goootrafego.com/checkout/5dda1673-fe9d-4635-86da-25512f2ff275",
        videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        destaque: false
    }
];
